"""
This type stub file was generated by pyright.
"""

from typing import Dict, Iterable, Optional
from ..action import Action
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType

"""
This type stub file was generated by pyright.
"""
_executable_process_counter_lock = ...
_executable_process_counter = ...
class Executable:
    """Describes an executable (usually a single process) which may be run by the launch system."""
    def __init__(self, *, cmd: Iterable[SomeSubstitutionsType], prefix: Optional[SomeSubstitutionsType] = ..., name: Optional[SomeSubstitutionsType] = ..., cwd: Optional[SomeSubstitutionsType] = ..., env: Optional[Dict[SomeSubstitutionsType, SomeSubstitutionsType]] = ..., additional_env: Optional[Dict[SomeSubstitutionsType, SomeSubstitutionsType]] = ..., arguments: Optional[Iterable[SomeSubstitutionsType]] = ...) -> None:
        """
        Initialize an Executable description.

        :param cmd: A list where the first item is the executable and the rest are
            arguments to the executable, each item may be a string or a list of strings
            and Substitutions to be resolved at runtime
        :param prefix: a set of commands/arguments to precede the cmd, used for
            things like gdb/valgrind and defaults to the LaunchConfiguration
            called 'launch-prefix'. Note that a non-default prefix provided in
            a launch file will override the prefix provided via the `launch-prefix`
            launch configuration regardless of whether the `launch-prefix-filter` launch
            configuration is provided.
        :param name: The label used to represent the process, as a string or a Substitution
            to be resolved at runtime, defaults to the basename of the executable
        :param cwd: The directory in which to run the executable
        :param env: Dictionary of environment variables to be used, starting from a clean
            environment. If None, the current environment of the launch context is used.
        :param additional_env: Dictionary of environment variables to be added. If env was
            None, they are added to the current environment. If not, env is updated with
            additional_env.
        :param arguments: list of extra arguments for the executable
        """
        ...
    
    @property
    def name(self) -> List[Substitution] | None:
        """Getter for name."""
        ...
    
    @property
    def prefix(self) -> List[Substitution]:
        """Getter for prefix."""
        ...
    
    @property
    def cmd(self) -> list[List[Substitution]]:
        """Getter for cmd."""
        ...
    
    @property
    def cwd(self) -> List[Substitution] | None:
        """Getter for cwd."""
        ...
    
    @property
    def env(self) -> List[Tuple[List[Substitution], List[Substitution]]] | None:
        """Getter for env."""
        ...
    
    @property
    def additional_env(self) -> List[Tuple[List[Substitution], List[Substitution]]] | None:
        """Getter for additional_env."""
        ...
    
    @property
    def arguments(self) -> Iterable[SomeSubstitutionsType] | None:
        """Getter for arguments."""
        ...
    
    @property
    def final_name(self) -> str | None:
        """Getter for final_name."""
        ...
    
    @property
    def final_cmd(self) -> List[str] | None:
        """Getter for final_cmd."""
        ...
    
    @property
    def final_cwd(self) -> str | None:
        """Getter for cwd."""
        ...
    
    @property
    def final_env(self) -> Dict[str, str] | None:
        """Getter for final_env."""
        ...
    
    def prepare(self, context: LaunchContext, action: Action) -> None:
        """
        Prepare an executable description for execution in a given environment.

        This does the following:
        - performs substitutions on various properties

        Note that 'action' is not used at this level; it is provided for use
        by subclasses which may override this method.
        """
        ...
    


