"""
This type stub file was generated by pyright.
"""

from typing import List, Union
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution
from ..utilities.type_utils import NormalizedValueType

"""
This type stub file was generated by pyright.
"""
@expose_action('append_env')
class AppendEnvironmentVariable(Action):
    """
    Action that appends to an environment variable if it exists and sets it if it does not.

    It can optionally prepend instead of appending.
    It can also optionally use a custom separator, with the default being a platform-specific
    separator, `os.pathsep`.
    """
    def __init__(self, name: SomeSubstitutionsType, value: SomeSubstitutionsType, prepend: Union[bool, SomeSubstitutionsType] = ..., separator: SomeSubstitutionsType = ..., **kwargs) -> None:
        """
        Create an AppendEnvironmentVariable action.

        All parameters can be provided as substitutions.
        A substitution for the prepend parameter will be coerced to `bool` following YAML rules.

        :param name: the name of the environment variable
        :param value: the value to set or append
        :param prepend: whether the value should be prepended instead
        :param separator: the separator to use, defaulting to a platform-specific separator
        """
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Parse an 'append_env' entity."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for the name of the environment variable to be set or appended to."""
        ...
    
    @property
    def value(self) -> List[Substitution]:
        """Getter for the value of the environment variable to be set or appended."""
        ...
    
    @property
    def prepend(self) -> NormalizedValueType:
        """Getter for the prepend flag."""
        ...
    
    @property
    def separator(self) -> List[Substitution]:
        """Getter for the separator."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


