"""
This type stub file was generated by pyright.
"""

from ..action import Action
from ..event import Event
from ..launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
class EmitEvent(Action):
    """Action that emits an event when executed."""
    def __init__(self, *, event: Event, **kwargs) -> None:
        """Create an EmitEvent action."""
        ...
    
    @property
    def event(self) -> Event:
        """Getter for self.__event."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


