"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Callable, Dict, List, Optional, Text, Union
from osrf_pycommon.process_utils import AsyncSubprocessProtocol
from ..action import Action
from ..descriptions import Executable
from ..events.process import ProcessExited
from ..launch_context import LaunchContext
from ..launch_description_entity import LaunchDescriptionEntity
from ..some_entities_type import SomeEntitiesType
from ..some_substitutions_type import SomeSubstitutionsType

"""
This type stub file was generated by pyright.
"""
class ExecuteLocal(Action):
    """Action that begins executing a process on the local system and sets up event handlers."""
    def __init__(self, *, process_description: Executable, shell: bool = ..., sigterm_timeout: SomeSubstitutionsType = ..., sigkill_timeout: SomeSubstitutionsType = ..., emulate_tty: bool = ..., output: SomeSubstitutionsType = ..., output_format: Text = ..., cached_output: bool = ..., log_cmd: bool = ..., on_exit: Optional[Union[SomeEntitiesType, Callable[[ProcessExited, LaunchContext], Optional[SomeEntitiesType]]]] = ..., respawn: Union[bool, SomeSubstitutionsType] = ..., respawn_delay: Optional[float] = ..., respawn_max_retries: int = ..., **kwargs) -> None:
        """
        Construct an ExecuteLocal action.

        Many arguments are passed eventually to :class:`subprocess.Popen`, so
        see the documentation for the class for additional details.

        This action, once executed, registers several event handlers for
        various process related events and will also emit events asynchronously
        when certain events related to the process occur.

        Handled events include:

        - launch.events.process.ShutdownProcess:

          - begins standard shutdown procedure for a running executable

        - launch.events.process.SignalProcess:

          - passes the signal provided by the event to the running process

        - launch.events.process.ProcessStdin:

          - passes the text provided by the event to the stdin of the process

        - launch.events.Shutdown:

          - same as ShutdownProcess

        Emitted events include:

        - launch.events.process.ProcessStarted:

            - emitted when the process starts

        - launch.events.process.ProcessExited:

            - emitted when the process exits
            - event contains return code

        - launch.events.process.ProcessStdout and launch.events.process.ProcessStderr:

            - emitted when the process produces data on either the stdout or stderr pipes
            - event contains the data from the pipe

        Note that output is just stored in this class and has to be properly
        implemented by the event handlers for the process's ProcessIO events.

        :param: process_description the `launch.descriptions.Executable` to execute
            as a local process
        :param: shell if True, a shell is used to execute the cmd
        :param: sigterm_timeout time until shutdown should escalate to SIGTERM,
            as a string or a list of strings and Substitutions to be resolved
            at runtime, defaults to the LaunchConfiguration called
            'sigterm_timeout'
        :param: sigkill_timeout time until escalating to SIGKILL after SIGTERM,
            as a string or a list of strings and Substitutions to be resolved
            at runtime, defaults to the LaunchConfiguration called
            'sigkill_timeout'
        :param: emulate_tty emulate a tty (terminal), defaults to False, but can
            be overridden with the LaunchConfiguration called 'emulate_tty',
            the value of which is evaluated as true or false according to
            :py:func:`evaluate_condition_expression`.
            Throws :py:exc:`InvalidConditionExpressionError` if the
            'emulate_tty' configuration does not represent a boolean.
        :param: output configuration for process output logging. Defaults to 'log'
            i.e. log both stdout and stderr to launch main log file and stderr to
            the screen.
            Overridden externally by the OVERRIDE_LAUNCH_PROCESS_OUTPUT envvar value.
            See `launch.logging.get_output_loggers()` documentation for further
            reference on all available options.
        :param: output_format for logging each output line, supporting `str.format()`
            substitutions with the following keys in scope: `line` to reference the raw
            output line and `this` to reference this action instance.
        :param: log_cmd if True, prints the final cmd before executing the
            process, which is useful for debugging when substitutions are
            involved.
        :param: cached_output if `True`, both stdout and stderr will be cached.
            Use get_stdout() and get_stderr() to read the buffered output.
        :param: on_exit list of actions to execute upon process exit.
        :param: respawn if 'True', relaunch the process that abnormally died.
            Either a boolean or a Substitution to be resolved at runtime. Defaults to 'False'.
        :param: respawn_delay a delay time to relaunch the died process if respawn is 'True'.
        :param: respawn_max_retries number of times to respawn the process if respawn is 'True'.
                A negative value will respawn an infinite number of times (default behavior).
        """
        ...
    
    @property
    def process_description(self) -> Executable:
        """Getter for process_description."""
        ...
    
    @property
    def shell(self) -> bool:
        """Getter for shell."""
        ...
    
    @property
    def emulate_tty(self) -> bool:
        """Getter for emulate_tty."""
        ...
    
    @property
    def sigkill_timeout(self) -> List[Substitution]:
        """Getter for sigkill timeout."""
        ...
    
    @property
    def sigterm_timeout(self) -> List[Substitution]:
        """Getter for sigterm timeout."""
        ...
    
    @property
    def output(self) -> dict[Any, Any] | List[Substitution]:
        """Getter for output."""
        ...
    
    @property
    def process_details(self) -> Dict[Text, Any] | None:
        """Getter for the process details, e.g. name, pid, cmd, etc., or None if not started."""
        ...
    
    def get_sub_entities(self) -> list[LaunchDescriptionEntity] | list[Any]:
        ...
    
    class __ProcessProtocol(AsyncSubprocessProtocol):
        def __init__(self, action: ExecuteLocal, context: LaunchContext, process_event_args: Dict, **kwargs) -> None:
            ...
        
        def connection_made(self, transport) -> None:
            ...
        
        def on_stdout_received(self, data: bytes) -> None:
            ...
        
        def on_stderr_received(self, data: bytes) -> None:
            ...
        
    
    
    def prepare(self, context: LaunchContext) -> None:
        """Prepare the action for execution."""
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[LaunchDescriptionEntity]]:
        """
        Execute the action.

        This does the following:
        - register an event handler for the shutdown process event
        - register an event handler for the signal process event
        - register an event handler for the stdin event
        - configures logging for the IO process event
        - create a task for the coroutine that monitors the process
        """
        ...
    
    def get_asyncio_future(self) -> Optional[asyncio.Future]:
        """Return an asyncio Future, used to let the launch system know when we're done."""
        ...
    
    def get_stdout(self) -> str:
        """
        Get cached stdout.

        :raises RuntimeError: if cached_output is false.
        """
        ...
    
    def get_stderr(self) -> str:
        """
        Get cached stdout.

        :raises RuntimeError: if cached_output is false.
        """
        ...
    
    @property
    def return_code(self) -> None:
        """Get the process return code, None if it hasn't finished."""
        ...
    


