"""
This type stub file was generated by pyright.
"""

from typing import Dict, Iterable, List, Optional
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..launch_description_entity import LaunchDescriptionEntity
from ..some_substitutions_type import SomeSubstitutionsType

"""
This type stub file was generated by pyright.
"""
@expose_action('group')
class GroupAction(Action):
    """
    Action that yields other actions.

    This action is used to nest other actions without including a separate
    launch description, while also optionally having a condition (like all
    other actions), scoping and forwarding launch configurations and
    environment variables, and/or declaring launch configurations for just the
    group and its yielded actions.

    When scoped=True, changes to launch configurations and environment
    variables are limited to the scope of actions in the group action.

    When scoped=True and forwarding=True, all existing launch configurations
    and environment variables are available in the scoped context.

    When scoped=True and forwarding=False, all existing launch configurations
    and environment variables are removed from the scoped context.

    Any launch configuration defined in the launch_configurations dictionary
    will be set in the current context.
    When scoped=False these configurations will persist even after the
    GroupAction has completed.
    When scoped=True these configurations will only be available to actions in
    the GroupAction.
    When scoped=True and forwarding=False, the launch_configurations dictionary
    is evaluated before clearing, and then re-set in the cleared scoped context.
    """
    def __init__(self, actions: Iterable[Action], *, scoped: bool = ..., forwarding: bool = ..., launch_configurations: Optional[Dict[SomeSubstitutionsType, SomeSubstitutionsType]] = ..., **left_over_kwargs) -> None:
        """Create a GroupAction."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `GroupAction` action and kwargs for constructing it."""
        ...
    
    def get_sub_entities(self) -> List[LaunchDescriptionEntity]:
        """Return subentities."""
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[LaunchDescriptionEntity]]:
        """Execute the action."""
        ...
    


