"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Optional, Sequence, Tuple, Union
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..launch_description_entity import LaunchDescriptionEntity
from ..launch_description_source import LaunchDescriptionSource
from ..some_substitutions_type import SomeSubstitutionsType

"""
This type stub file was generated by pyright.
"""
@expose_action('include')
class IncludeLaunchDescription(Action):
    """
    Action that includes a launch description source and yields its entities when visited.

    It is possible to pass arguments to the launch description, which it
    declared with the :py:class:`launch.actions.DeclareLaunchArgument` action.

    If any given arguments do not match the name of any declared launch
    arguments, then they will still be set as Launch Configurations using the
    :py:class:`launch.actions.SetLaunchConfiguration` action.
    This is done because it's not always possible to detect all instances of
    the declare launch argument class in the given launch description.

    On the other side, an error will sometimes be raised if the given launch
    description declares a launch argument and its value is not provided to
    this action.
    It will only produce this error, however, if the declared launch argument
    is unconditional (sometimes the action that declares the launch argument
    will only be visited in certain circumstances) and if it does not have a
    default value on which to fall back.

    Conditionally included launch arguments that do not have a default value
    will eventually raise an error if this best effort argument checking is
    unable to see an unsatisfied argument ahead of time.

    For example, to include ``my_pkg``'s ``other_launch.py`` and set launch arguments for it:

    .. code-block:: python

        def generate_launch_description():
            return ([
                SetLaunchConfiguration('arg1', 'value1'),
                IncludeLaunchDescription(
                    AnyLaunchDescriptionSource([
                        PathJoinSubstitution([
                            FindPackageShare('my_pkg'),
                            'launch',
                            'other_launch.py',
                        ]),
                    ]),
                    launch_arguments={
                        'other_arg1': LaunchConfiguration('arg1'),
                        'other_arg2': 'value2',
                    }.items(),
                ),
            ])

    .. code-block:: xml

        <launch>
            <let name="arg1" value="value1" />
            <include file="$(find-pkg-share my_pkg)/launch/other_launch.py">
                <let name="other_arg1" value="$(var arg1)" />
                <let name="other_arg2" value="value2" />
            </include>
        </launch>

    .. code-block:: yaml

        launch:
        - let:
            name: 'arg1'
            value: 'value1'
        - include:
            file: '$(find-pkg-share my_pkg)/launch/other_launch.py'
            let:
                - name: 'other_arg1'
                  value: '$(var arg1)'
                - name: 'other_arg2'
                  value: 'value2'

    .. note::

        While frontends currently support both ``let`` and ``arg`` for launch arguments, they are
        both converted into ``SetLaunchConfiguration`` actions (``let``). The same launch argument
        should not be defined using both ``let`` and ``arg``.
    """
    def __init__(self, launch_description_source: Union[LaunchDescriptionSource, SomeSubstitutionsType], *, launch_arguments: Optional[Iterable[Tuple[SomeSubstitutionsType, SomeSubstitutionsType]]] = ..., **kwargs) -> None:
        """Create an IncludeLaunchDescription action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `IncludeLaunchDescription` action and kwargs for constructing it."""
        ...
    
    @property
    def launch_description_source(self) -> LaunchDescriptionSource:
        """Getter for self.__launch_description_source."""
        ...
    
    @property
    def launch_arguments(self) -> Sequence[Tuple[SomeSubstitutionsType, SomeSubstitutionsType]]:
        """Getter for self.__launch_arguments."""
        ...
    
    def get_sub_entities(self) -> list[LaunchDescription]:
        """Get subentities."""
        ...
    
    def execute(self, context: LaunchContext) -> List[LaunchDescriptionEntity]:
        """Execute the action."""
        ...
    


