"""
This type stub file was generated by pyright.
"""

from typing import List
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""
This type stub file was generated by pyright.
"""
@expose_action('log')
class LogInfo(Action):
    """Action that logs a message when executed."""
    def __init__(self, *, msg: SomeSubstitutionsType, **kwargs) -> None:
        """Create a LogInfo action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Parse `log` tag."""
        ...
    
    @property
    def msg(self) -> List[Substitution]:
        """Getter for self.__msg."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


