"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any, Awaitable, Callable, Dict, Iterable, List, Optional, Text
from ..action import Action
from ..launch_context import LaunchContext
from ..launch_description_entity import LaunchDescriptionEntity

"""
This type stub file was generated by pyright.
"""
class OpaqueCoroutine(Action):
    """
    Action that adds a Python coroutine function to the launch run loop.

    The signature of the coroutine function should be:

    .. code-block:: python

        async def coroutine_func(
            context: LaunchContext,
            *args,
            **kwargs
        ):
            ...

    if ignore_context is False on construction (currently the default), or

    .. code-block:: python

        async def coroutine_func(
            *args,
            **kwargs
        ):
            ...

    if ignore_context is True on construction.
    """
    def __init__(self, *, coroutine: Callable[..., Awaitable[None]], args: Optional[Iterable[Any]] = ..., kwargs: Optional[Dict[Text, Any]] = ..., ignore_context: bool = ..., **left_over_kwargs) -> None:
        """Create an OpaqueCoroutine action."""
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[LaunchDescriptionEntity]]:
        """Execute the action."""
        ...
    
    def get_asyncio_future(self) -> Optional[asyncio.Future]:
        """Return an asyncio Future, used to let the launch system know when we're done."""
        ...
    


