"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Iterable, List, Optional, Text
from ..action import Action
from ..launch_context import LaunchContext
from ..launch_description_entity import LaunchDescriptionEntity

"""
This type stub file was generated by pyright.
"""
class OpaqueFunction(Action):
    """
    Action that executes a Python function.

    The signature of the function should be:

    .. code-block:: python

        def function(
            context: LaunchContext,
            *args,
            **kwargs
        ) -> Optional[List[LaunchDescriptionEntity]]:
            ...

    """
    def __init__(self, *, function: Callable, args: Optional[Iterable[Any]] = ..., kwargs: Optional[Dict[Text, Any]] = ..., **left_over_kwargs) -> None:
        """Create an OpaqueFunction action."""
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[LaunchDescriptionEntity]]:
        """Execute the action."""
        ...
    


