"""
This type stub file was generated by pyright.
"""

from ..action import Action
from ..launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
class PopLaunchConfigurations(Action):
    """
    Action that pops the state of launch configurations from a stack.

    The state can be stored initially by pushing onto the stack with the
    :py:class:`launch.actions.PushLaunchConfigurations` action.
    """
    def __init__(self, **kwargs) -> None:
        """Create a PopLaunchConfigurations action."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


