"""
This type stub file was generated by pyright.
"""

from ..action import Action
from ..launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
class PushLaunchConfigurations(Action):
    """
    Action that pushes the current state of launch configurations to a stack.

    The state can be restored by popping the stack with the
    :py:class:`launch.actions.PopLaunchConfigurations` action.
    """
    def __init__(self, **kwargs) -> None:
        """Create a PushLaunchConfigurations action."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


