"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Text, Tuple
from ..action import Action
from ..event_handler import BaseEventHandler
from ..launch_context import LaunchContext
from ..launch_description_entity import LaunchDescriptionEntity

"""
This type stub file was generated by pyright.
"""
class RegisterEventHandler(Action):
    """
    Action that registers an event handler.

    Event handlers that are registered in this action will not be matched
    to an event that is in the process of being handled.
    For example, if you have an event handler for event 'Foo', which returns
    an instance of RegisterEventHandler for a new event handler that handles
    the event 'Foo' as well, that event handler will not be matched with the
    instance of the 'Foo' event that caused it to be registered in the first
    place.
    """
    def __init__(self, event_handler: BaseEventHandler, **kwargs) -> None:
        """Create a RegisterEventHandler action."""
        ...
    
    @property
    def event_handler(self) -> BaseEventHandler:
        """Getter for self.__event_handler."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    
    def describe_conditional_sub_entities(self) -> List[Tuple[Text, Iterable[LaunchDescriptionEntity],]]:
        ...
    


