"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType

"""
This type stub file was generated by pyright.
"""
@expose_action('reset')
class ResetLaunchConfigurations(Action):
    """
    Action that resets launch configurations in the current context.

    This action can be used to clear the launch configurations from the
    context it was called in.
    It optionally can be given a dictionary with launch configurations
    to be set after clearing.
    Launch configurations given in the dictionary are evaluated before
    the context launch configurations are cleared.
    This allows launch configurations to be passed through the clearing
    of the context.

    If launch_configurations is None or an empty dict then all launch configurations
    will be cleared.

    If launch_configurations has entries (i.e. {'foo': 'FOO'}) then these will be
    set after the clearing operation.
    """
    def __init__(self, launch_configurations: Optional[Dict[SomeSubstitutionsType, SomeSubstitutionsType]] = ..., **kwargs) -> None:
        """Create an ResetLaunchConfigurations action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `ResetLaunchConfigurations` action and kwargs for constructing it."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


