"""
This type stub file was generated by pyright.
"""

from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
@expose_action('reset_env')
class ResetEnvironment(Action):
    """
    Action that resets the environment in the current context.

    Clears any changes made by previous actions to the context environment.
    The environment is reset to the state it was in when the context was created,
    i.e. the contents of ``os.environ``.
    """
    def __init__(self, **kwargs) -> None:
        """Create a ResetEnvironment action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return ``ResetEnvironment`` action and kwargs for constructing it."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


