"""
This type stub file was generated by pyright.
"""

from typing import List
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""
This type stub file was generated by pyright.
"""
@expose_action('set_env')
class SetEnvironmentVariable(Action):
    """Action that sets an environment variable."""
    def __init__(self, name: SomeSubstitutionsType, value: SomeSubstitutionsType, **kwargs) -> None:
        """Create a SetEnvironmentVariable action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Parse a 'set_env' entity."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for the name of the environment variable to be set."""
        ...
    
    @property
    def value(self) -> List[Substitution]:
        """Getter for the value of the environment variable to be set."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


