"""
This type stub file was generated by pyright.
"""

from typing import List
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""
This type stub file was generated by pyright.
"""
@expose_action('let')
class SetLaunchConfiguration(Action):
    """
    Action that sets a launch configuration by name.

    Launch configurations can be accessed by the LaunchConfiguration
    substitution and are accessible after being set, even in included
    LaunchDescription's, but can be scoped with groups.
    """
    def __init__(self, name: SomeSubstitutionsType, value: SomeSubstitutionsType, **kwargs) -> None:
        """Create a SetLaunchConfiguration action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `SetLaunchConfiguration` action and kwargs for constructing it."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for self.__name."""
        ...
    
    @property
    def value(self) -> List[Substitution]:
        """Getter for self.__value."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


