"""
This type stub file was generated by pyright.
"""

from typing import Text
from launch.frontend import Entity, Parser, expose_action
from .emit_event import EmitEvent
from ..launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
_logger = ...
@expose_action('shutdown')
class Shutdown(EmitEvent):
    """Action that shuts down a launched system by emitting Shutdown when executed."""
    def __init__(self, *, reason: Text = ..., **kwargs) -> None:
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `Shutdown` action and kwargs for constructing it."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


