"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Iterable, List, Optional, Text, Tuple, Union
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..launch_description_entity import LaunchDescriptionEntity
from ..some_entities_type import SomeEntitiesType
from ..some_substitutions_type import SomeSubstitutionsType

"""
This type stub file was generated by pyright.
"""
@expose_action('timer')
class TimerAction(Action):
    """
    Action that defers other entities until a period of time has passed, unless canceled.

    All timers are "one-shot", in that they only fire one time and never again.

    Entities executed after the given period of time can access the launch configurations that
    exist at the time that the timer action executed, but changes made by them will not persist.
    This is similar to grouping the entities in a :class:`launch.actions.GroupAction` with
    ``scoped=True``.
    """
    def __init__(self, *, period: Union[float, SomeSubstitutionsType], actions: Iterable[LaunchDescriptionEntity], cancel_on_shutdown: Union[bool, SomeSubstitutionsType] = ..., **kwargs) -> None:
        """
        Create a TimerAction.

        :param period: the time (in seconds) to set the timer for
        :param actions: an iterable containing actions to be executed on timeout
        :param cancel_on_shutdown: whether to cancel the timer on launch shutdown
        """
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return the `Timer` action and kwargs for constructing it."""
        ...
    
    @property
    def period(self) -> NormalizedValueType:
        ...
    
    @property
    def actions(self) -> Iterable[LaunchDescriptionEntity]:
        ...
    
    def describe(self) -> Text:
        """Return a description of this TimerAction."""
        ...
    
    def describe_conditional_sub_entities(self) -> List[Tuple[Text, Iterable[LaunchDescriptionEntity],]]:
        """Return the actions that will result when the timer expires, but was not canceled."""
        ...
    
    def handle(self, context: LaunchContext) -> Optional[SomeEntitiesType]:
        """Handle firing of timer."""
        ...
    
    def cancel(self) -> None:
        """
        Cancel this TimerAction.

        Calling cancel will not fail if the timer has already finished or
        already been canceled or if the timer has not been started yet.

        This function is not thread-safe and should be called only from under
        another coroutine.
        """
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[LaunchDescriptionEntity]]:
        """
        Execute the action.

        This does the following:
        - register a global event handler for TimerAction's if not already done
        - create a task for the coroutine that waits until canceled or timeout
        - coroutine asynchronously fires event after timeout, if not canceled
        """
        ...
    
    def get_asyncio_future(self) -> Optional[asyncio.Future]:
        """Return an asyncio Future, used to let the launch system know when we're done."""
        ...
    


