"""
This type stub file was generated by pyright.
"""

from ..action import Action
from ..event_handler import BaseEventHandler
from ..launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
class UnregisterEventHandler(Action):
    """Action that unregisters an event handler."""
    def __init__(self, event_handler: BaseEventHandler, **kwargs) -> None:
        """Create an UnregisterEventHandler action."""
        ...
    
    @property
    def event_handler(self) -> BaseEventHandler:
        """Getter for self.__event_handler."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """
        Execute the action.

        :raises ValueError: if the event handler has not been previously registered.
        """
        ...
    


