"""
This type stub file was generated by pyright.
"""

from typing import List
from ..action import Action
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""
This type stub file was generated by pyright.
"""
class UnsetLaunchConfiguration(Action):
    """
    Action that unsets a launch configuration by name.

    If the given launch configuration name is no set already then nothing
    happens.

    /sa :py:class:`launch.actions.SetLaunchConfiguration`
    """
    def __init__(self, name: SomeSubstitutionsType, **kwargs) -> None:
        """Create an UnsetLaunchConfiguration action."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for self.__name."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


