"""
This type stub file was generated by pyright.
"""

from typing import List
from ..action import Action
from ..frontend import Entity, Parser, expose_action
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""
This type stub file was generated by pyright.
"""
@expose_action('unset_env')
class UnsetEnvironmentVariable(Action):
    """Action that unsets an environment variable if it is set, otherwise does nothing."""
    def __init__(self, name: SomeSubstitutionsType, **kwargs) -> None:
        """Create an UnsetEnvironmentVariable action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Parse a 'set_env' entity."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for the name of the environment variable to be unset."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


