"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Text, Type, TypeVar, overload

"""
This type stub file was generated by pyright.
"""
TargetType = TypeVar('TargetType')
class Entity:
    """Single item in the intermediate front_end representation."""
    @property
    def type_name(self) -> Text:
        """Get Entity type."""
        ...
    
    @property
    def parent(self) -> Optional[Entity]:
        """Get Entity parent."""
        ...
    
    @property
    def children(self) -> List[Entity]:
        """Get the Entity's children."""
        ...
    
    @overload
    def get_attr(self, name: Text, *, data_type: Type[TargetType], optional: bool, can_be_str: bool = ...) -> Optional[TargetType]:
        ...
    
    @overload
    def get_attr(self, name: Text, *, data_type: Type[TargetType], can_be_str: bool = ...) -> TargetType:
        ...
    
    @overload
    def get_attr(self, name: Text, *, optional: bool, can_be_str: bool = ...) -> Optional[str]:
        ...
    
    @overload
    def get_attr(self, name: Text, *, can_be_str: bool = ...) -> str:
        ...
    
    def get_attr(self, name, *, data_type=..., optional=..., can_be_str=...):
        """
        Access an attribute of the entity.

        By default, it will try to return it as an string.
        `data_type` is the expected type of the attribute. Type coercion or type checking is
        applied depending on the particular frontend.

        See :py:obj:`launch.utilities.AllowedTypesTuple` to see what types are allowed.

        `data_type = None` will result in yaml parsing of the attribute value as a string.

        `List[Entity]` allows accessing a list of subentities with an specific name.

        Check the documentation of each specific frontend implementation to see how a list of
        attributes or `List[Entity]` look like.

        If `optional` is `True` and the attribute cannot be found, `None` will be returned
        instead of raising `AttributeError`.

        :param name: name of the attribute
        :param data_type: type of the attribute to be read. Defaults to 'str'
        :param optional: when `True`, it doesn't raise an error when the attribute is not found.
            It returns `None` instead. Defaults to `False`
        :raises `AttributeError`: Attribute not found. Only possible if `optional` is `False`
        :raises `TypeError`: Attribute found but it is not of the correct type.
            Only happens in frontend implementations that do type checking
        :raises `ValueError`: Attribute found but can't be coerced to one of the specified types.
            Only happens in frontend implementations that do type coercion.
        """
        ...
    
    def assert_entity_completely_parsed(self):
        """
        Assert that all attributes and children of the entity were parsed.

        This function is automatically called after the `parse(entity, parser)`
        function completed.
        """
        ...
    


