"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Iterable, Optional, Text
from ..action import Action
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""
This type stub file was generated by pyright.
"""
if False:
    ...
action_parse_methods: Dict[str, Any] = ...
substitution_parse_methods: Dict[str, Any] = ...
def instantiate_action(entity: Entity, parser: Parser) -> Action:
    """Call the registered parsing method for the `Entity`."""
    ...

def instantiate_substitution(type_name: Text, args: Optional[Iterable[SomeSubstitutionsType]] = ...) -> Substitution:
    """Call the registered substitution parsing method, according to `args`."""
    ...

def expose_substitution(name: Text) -> Callable[..., type[Any] | FunctionType | Any]:
    """
    Return a decorator for exposing a substitution.

    Read __expose_impl documentation.
    """
    ...

def expose_action(name: Text) -> Callable[..., type[Any] | FunctionType | Any]:
    """
    Return a decorator for exposing an action.

    Read __expose_impl documentation.
    """
    ...

