"""
This type stub file was generated by pyright.
"""

import sys
from typing import List, Optional, Set, TYPE_CHECKING, Text, TextIO, Tuple, Type, Union
from .entity import Entity
from ..action import Action
from ..invalid_launch_file_error import InvalidLaunchFileError
from ..substitution import Substitution
from ..utilities.type_utils import NormalizedValueType, StrSomeValueType
from ..utilities.typing_file_path import FilePath
from ..launch_description import LaunchDescription

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 8):
    ...
else:
    ...
if TYPE_CHECKING:
    ...
class InvalidFrontendLaunchFileError(InvalidLaunchFileError):
    """Exception raised when the given frontend launch file is not valid."""
    ...


class Parser:
    """
    Abstract class for parsing launch actions, substitutions and descriptions.

    Implementations of the parser class, should override the load method.
    They could also override the parse_substitution and/or get_file_extensions methods, or not.
    load_launch_extensions, parse_action, parse_description, get_available_extensions, may_parse,
    is_filename_valid, get_parsers_from_filename and get_file_extensions_from_parsers are not
    supposed to be overridden.
    """
    extensions_loaded = ...
    frontend_parsers = ...
    @classmethod
    def load_launch_extensions(cls) -> None:
        """Load launch extensions, in order to get all the exposed substitutions and actions."""
        ...
    
    @classmethod
    def load_parser_implementations(cls) -> None:
        """Load all the available frontend entities."""
        ...
    
    def parse_action(self, entity: Entity) -> Action:
        """Parse an action, using its registered parsing method."""
        ...
    
    def parse_substitution(self, value: Text) -> List[Substitution]:
        """Parse a substitution."""
        ...
    
    def parse_if_substitutions(self, value: StrSomeValueType) -> NormalizedValueType:
        """See :py:func:`launch.frontend.parser.parse_if_substitutions`."""
        ...
    
    def escape_characters(self, value: Text) -> Text:
        """Escape characters in strings."""
        ...
    
    def parse_description(self, entity: Entity) -> LaunchDescription:
        """Parse a launch description."""
        ...
    
    @classmethod
    def get_available_extensions(cls) -> List[Text]:
        """Return the registered extensions."""
        ...
    
    @classmethod
    def is_extension_valid(cls, extension: Text) -> bool:
        """Return an entity loaded with a markup file."""
        ...
    
    @classmethod
    def get_parser_from_extension(cls, extension: Text) -> Optional[Type[Parser]]:
        """Return an entity loaded with a markup file."""
        ...
    
    @classmethod
    def may_parse(cls, filename: Text) -> bool:
        """Return `True` if the filename is valid for this parser."""
        ...
    
    @classmethod
    def is_filename_valid(cls, filename: Text) -> bool:
        """Return `True` if the filename is valid for any parser."""
        ...
    
    @classmethod
    def get_parsers_from_filename(cls, filename: Text) -> List[Type[Parser]]:
        """Return a list of parsers which entity loaded with a markup file."""
        ...
    
    @classmethod
    def get_file_extensions_from_parsers(cls) -> Set[Type[Parser]]:
        """Return a set of file extensions known to the parser implementations."""
        ...
    
    @classmethod
    def load(cls, file: Union[FilePath, TextIO]) -> Tuple[Entity, Parser]:
        """
        Parse an Entity from a markup language-based launch file.

        Parsers are exposed and provided by available frontend implementations.
        To choose the right parser, it'll first attempt to infer the launch
        description format based on the filename extension, if any.
        If format inference fails, it'll try all available parsers one after the other.
        """
        ...
    
    @classmethod
    def get_file_extensions(cls) -> Set[Text]:
        """Return the set of file extensions known to this parser."""
        ...
    


