"""
This type stub file was generated by pyright.
"""

from typing import List, Text, Type, Union
from .entity import Entity
from ..utilities.type_utils import AllowedTypesType

"""
This type stub file was generated by pyright.
"""
def check_is_list_entity(data_type: Union[AllowedTypesType, Type[List[Entity]]]) -> bool:
    """Check if `data_type` is a `typing.List` with elements of `Entity` type or derived."""
    ...

def get_data_type_from_identifier(type_identifier: Text) -> type[str] | type[bool] | type[float] | type[int] | type[List[str]] | type[List[bool]] | type[List[float]] | type[List[int]] | None:
    ...

