"""
This type stub file was generated by pyright.
"""

from .evaluate_parameters import evaluate_parameters
from .lifecycle_event_manager import LifecycleEventManager
from .namespace_utils import is_namespace_absolute, is_root_namespace, make_namespace_absolute, prefix_namespace
from .normalize_parameters import normalize_parameters
from .normalize_remap_rule import normalize_remap_rule, normalize_remap_rules
from .to_parameters_list import to_parameters_list
from .track_node_names import add_node_name, get_node_name_count

"""
Module for descriptions of launchable entities.

Descriptions are not executable and are immutable so they can be reused by launch entities.
"""
__all__ = ['add_node_name', 'evaluate_parameters', 'evaluate_parameters_dict', 'get_node_name_count', 'is_namespace_absolute', 'is_root_namespace', 'LifecycleEventManager', 'make_namespace_absolute', 'normalize_parameters', 'normalize_parameters_dict', 'normalize_remap_rule', 'normalize_remap_rules', 'prefix_namespace', 'to_parameters_list']
