"""
This type stub file was generated by pyright.
"""

from typing import Dict
from launch.launch_context import LaunchContext
from ..parameters_type import EvaluatedParameterValue, EvaluatedParameters, Parameters, ParametersDict

"""Module with utility for evaluating parameters in a launch context."""
def evaluate_parameter_dict(context: LaunchContext, parameters: ParametersDict) -> Dict[str, EvaluatedParameterValue]:
    ...

def evaluate_parameters(context: LaunchContext, parameters: Parameters) -> EvaluatedParameters:
    """
    Evaluate substitutions to produce paths and name/value pairs.

    The parameters must have been normalized with normalize_parameters() prior to calling this.
    Substitutions for parameter values in dictionaries will be evaluated according to yaml rules.
    If you want the substitution to stay a string, the output of the substition must have quotes.

    :param parameters: normalized parameters
    :returns: values after evaluating lists of substitutions
    """
    ...

