"""
This type stub file was generated by pyright.
"""

import launch

"""Module for the management of LifecycleNode events."""
class LifecycleEventManager:
    def __init__(self, lifecycle_node) -> None:
        """
        Construct a LifecycleEventManager utility.

        This utility emits some event(s) in certain circumstances:

        - :class:`launch.events.lifecycle.StateTransition`:

            - this event is emitted when a message is published to the
              "/<name>/transition_event" topic, indicating the lifecycle
              node represented by this action changed state

        This utility also handles some events related to lifecycle:

        - :class:`launch.events.lifecycle.ChangeState`

          - this event can be targeted to a single lifecycle node, or more than
            one, or even all lifecycle nodes, and it requests the targeted nodes
            to change state, see its documentation for more details.

        :param lifecycle_node: The lifecycle node to event manage.
        """
        ...
    
    @property
    def node_name(self):
        ...
    
    def setup_lifecycle_manager(self, context: launch.LaunchContext) -> None:
        ...
    


