"""
This type stub file was generated by pyright.
"""

from typing import Optional, Text, Type, TypeVar

"""Module with utility functions for handling namespaces."""
def is_root_namespace(ns: Text) -> bool:
    """Return `True` if `ns` is `'/'`."""
    ...

def is_namespace_absolute(ns: Text) -> bool:
    """Return `True` if `ns` is absolute."""
    ...

def prefix_namespace(base_ns: Optional[Text], ns: Optional[Text]) -> Optional[Text]:
    """
    Return `ns` prefixed with `base_ns` if `ns` is relative, return `ns` if not.

    :param `base_ns`: Prefix to be added to `ns`.
    :param `ns`: Namespace to be prefixed.
    :return: `None` if both `base_ns` and `ns` are `None`, or
        `base_ns` if `ns` is `None`, or
        `ns` if `base_ns` is `None`, or
        `ns` if `ns` is absolute, or
        `ns` prefixed with `base_ns`.
        In all cases, trailing `/` are stripped from the result.

    For example:

    .. code-block:: python

        combined_ns = prefix_namespace('my_ns', 'original_ns')
        assert combined_ns == 'my_ns/original_ns'

        combined_ns = prefix_namespace('/my_ns', 'original_ns')
        assert combined_ns == '/my_ns/original_ns'

        combined_ns = prefix_namespace('my_ns', '/original_ns')
        assert combined_ns == '/original_ns'

        combined_ns = prefix_namespace(None, 'original_ns')
        assert combined_ns == 'original_ns'

        combined_ns = prefix_namespace('my_ns', None)
        assert combined_ns == 'my_ns'
    """
    ...

OptionalText = TypeVar('OptionalText', Text, Type[None])
def make_namespace_absolute(ns: OptionalText) -> OptionalText:
    """Make a relative namespace absolute."""
    ...

