"""
This type stub file was generated by pyright.
"""

from ..remap_rule_type import RemapRule, RemapRules, SomeRemapRule, SomeRemapRules

"""Module for normalize_remap_rule utility."""
def normalize_remap_rule(remap_rule: SomeRemapRule) -> RemapRule:
    """Normalize a remap rule to a specific type."""
    ...

def normalize_remap_rules(remap_rules: SomeRemapRules) -> RemapRules:
    """Normalize multiple remap rules."""
    ...

