"""
This type stub file was generated by pyright.
"""

from typing import Optional, Sequence as SequenceTypeHint
from launch.substitution import Substitution
from ..parameters_type import Parameters, ParametersDict, SomeParameters, SomeParametersDict

"""Module with utility for normalizing parameters to a node."""
def normalize_parameter_dict(parameters: SomeParametersDict, *, _prefix: Optional[SequenceTypeHint[Substitution]] = ...) -> ParametersDict:
    """
    Normalize types used to store parameters in a dictionary.

    The parameters are passed as a dictionary that specifies parameter rules.
    Keys of the dictionary can be strings, a Substitution, or an iterable of Substitution.
    A normalized key will be a tuple of substitutions.
    Values in the dictionary can be strings, integers, floats, substitutions, lists of
    the previous types, or another dictionary with the same properties.

    Normalized values that were lists will have all subvalues converted to the same type.
    If all subvalues are int or float, then the normalized subvalues will all be float.
    If the subvalues otherwise do not all have the same type, then the normalized subvalues
    will be lists of Substitution that will result in a list of strings.

    Values that are a list of strings will become a list of strings when normalized and evaluated.
    Values that are a list which has at least one :class:`Substitution` and all other elements
    are either strings or a list of substitutions will become a single list of substitutions that
    will evaluate to a single string.
    To make a list of strings from substitutions, each item in the list must be a list or tuple.

    Normalized values that contained nested dictionaries will be collapsed into a single
    layer with parameter names concatenated with the parameter namespace separator ".".

    :param parameters: Parameters to be normalized
    :param _prefix: internal parameter used for flatening recursive dictionaries
    :return: Normalized parameters
    """
    ...

def normalize_parameters(parameters: SomeParameters) -> Parameters:
    """
    Normalize the types used to store parameters to substitution types.

    The passed parameters must be an iterable where each element is
    a path to a yaml file or a dict.
    The normalized parameters will have all paths converted to a list of :class:`Substitution`,
    and dictionaries normalized using :meth:`normalize_parameter_dict`.
    """
    ...

