"""
This type stub file was generated by pyright.
"""

class PluginException(Exception):
    """Base class for all exceptions within the plugin system."""
    ...


def satisfies_version(version, caret_range) -> None:
    ...

def get_upper_bound_caret_version(version) -> Version:
    ...

