"""
This type stub file was generated by pyright.
"""

import rclpy.parameter
from typing import List
from launch.launch_context import LaunchContext
from ..parameters_type import EvaluatedParameters

"""Module with utility to transform evaluated parameters into parameter lists."""
def is_node_name_matched(node_name: str, node_fqn: str) -> bool:
    ...

def to_parameters_list(context: LaunchContext, node_name: str, namespace: str, evaluated_parameters: EvaluatedParameters) -> List[rclpy.parameter.Parameter]:
    """
    Transform evaluated parameters into a list of rclpy.parameter.Parameter objects.

    :param context: to carry out substitutions during normalization of parameter files.
        See `normalize_parameters()` documentation for further reference.
    :param node_name: node name
    :param namespace: node namespace
    :param parameters: parameters as either paths to parameter files or name/value pairs.
        See `evaluate_parameters()` documentation for further reference.
    :returns: a list of parameters
    """
    ...

