"""
This type stub file was generated by pyright.
"""

from launch.launch_context import LaunchContext

"""Utility functions to help detect non-unique node names."""
def add_node_name(context: LaunchContext, node_name: str) -> None:
    """
    Add a node name to the context, indicating an occurrence of the node name.

    :param context: the context that keeps track of the node names
    :param node_name: the node name to keep track
    """
    ...

def get_node_name_count(context: LaunchContext, node_name: str) -> int:
    """
    Get the number of times the node name has occurred, according to the context.

    :param context: the context that keeps track of the node names
    :param node_name: the node name to keep track
    :returns: number of times the node name has occurred
    """
    ...

