"""
This type stub file was generated by pyright.
"""

from .executable_in_package import ExecutableInPackage
from .find_package import FindPackage, FindPackagePrefix, FindPackageShare
from .parameter import Parameter

"""substitutions Module."""
__all__ = ['ExecutableInPackage', 'FindPackage', 'FindPackagePrefix', 'FindPackageShare', 'Parameter']
