"""
This type stub file was generated by pyright.
"""

from typing import List, Sequence, Text
from launch.frontend import expose_substitution
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType
from launch.substitution import Substitution
from .find_package import FindPackagePrefix

"""Module for the ExecutableInPackage substitution."""
@expose_substitution('exec-in-pkg')
class ExecutableInPackage(FindPackagePrefix):
    """
    Substitution that tries to locate an executable in the libexec directory of a ROS package.

    The ROS package is located using ament_index_python.

    :raise: ament_index_python.packages.PackageNotFoundError when package is
        not found during substitution
    :raise: SubstitutionFailure when executable is not found, or package
        libexec directory doesn't exist, during substitution
    """
    def __init__(self, executable: SomeSubstitutionsType, package: SomeSubstitutionsType) -> None:
        """Create an ExecutableInPackage substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse a ExecutableInPackage substitution."""
        ...
    
    @property
    def executable(self) -> List[Substitution]:
        """Getter for executable."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by locating the executable."""
        ...
    


