"""
This type stub file was generated by pyright.
"""

from typing import List, Sequence, Text
from launch.frontend import expose_substitution
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType
from launch.substitution import Substitution
from launch.substitutions import PathSubstitution

"""Module for the FindPackage substitution."""
class FindPackage(PathSubstitution):
    """
    Abstract base class for substitutions involving finding a package.

    Subclasses should implement the find() method.
    """
    def __init__(self, package: SomeSubstitutionsType) -> None:
        """Create a FindPackage substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse a FindPackage substitution."""
        ...
    
    @property
    def package(self) -> List[Substitution]:
        """Getter for package."""
        ...
    
    def find(self, package_name: Text) -> Text:
        """
        Find a directory for a package.

        Called when the substitution is performed.

        :param: package_name The name of the package.
        :return: A directory related to the package.
        """
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by locating the package."""
        ...
    


@expose_substitution('find-pkg-prefix')
class FindPackagePrefix(FindPackage):
    """
    Substitution that tries to locate the package prefix of a ROS package.

    The ROS package is located using ament_index_python.

    :raise: ament_index_python.packages.PackageNotFoundError when package is
        not found during substitution.
    """
    def find(self, package_name: Text) -> Text:
        """Find the package prefix."""
        ...
    


@expose_substitution('find-pkg-share')
class FindPackageShare(FindPackage):
    """
    Substitution that tries to locate the share directory of a ROS package.

    The directory is located using ament_index_python.

    :raise: ament_index_python.packages.PackageNotFoundError when package is
        not found during substitution.
    """
    def find(self, package_name: Text) -> Text:
        """Find the share directory of a package."""
        ...
    


