"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, List, Optional, Sequence, Text, Union
from launch.frontend import expose_substitution
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType
from launch.substitution import Substitution

"""Module for the Parameter substitution."""
@expose_substitution('param')
class Parameter(Substitution):
    """
    Substitution that tries to get a parameter that was set by SetParameter.

    :raise: SubstitutionFailure when param is not found
    """
    def __init__(self, name: SomeSubstitutionsType, *, default: Optional[Union[Any, Iterable[Any]]] = ...) -> None:
        """Create a Parameter substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[Any, Any]]:
        """Parse a Parameter substitution."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for name."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution."""
        ...
    


