"""
This type stub file was generated by pyright.
"""

from typing import Callable, Text

"""Matchers for node names."""
if False:
    ...
def matches_node_name(node_name: Text) -> Callable[[Node], bool]:
    """Return a matcher which matches based on the name of the node itself."""
    ...

