"""
This type stub file was generated by pyright.
"""

"""Module for the class tools utility functions."""
def isclassinstance(obj) -> bool:
    """Return True if obj is an instance of a class."""
    ...

def is_a(obj, entity_type) -> bool:
    """Return True if obj is an instance of the entity_type class."""
    ...

def is_a_subclass(obj, entity_type) -> bool:
    """Return True if obj is an instance of the entity_type class or one of its subclass types."""
    ...

