"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, Optional, Text, Union

"""Module for the ensure_argument_type() utility function."""
def ensure_argument_type(argument: Any, types: Union[type, Iterable[type]], argument_name: Text, caller: Optional[Text] = ...) -> None:
    """
    Ensure that the given argument is an instance of or subclass of one of the given types.

    If the argument does not match one of the types, a TypeError is raised.
    The caller is included in the error message if given and not None.
    """
    ...

