"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List
from ..launch_description_entity import LaunchDescriptionEntity
from ..some_entities_type import SomeEntitiesType

"""Module for the normalize_to_list_of_entities() utility function."""
def normalize_to_list_of_entities(entities: Iterable[SomeEntitiesType]) -> List[LaunchDescriptionEntity]:
    """Return a list of Substitutions given a variety of starting inputs."""
    ...

