"""
This type stub file was generated by pyright.
"""

from typing import List
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the normalize_to_list_of_substitutions() utility function."""
def normalize_to_list_of_substitutions(subs: SomeSubstitutionsType) -> List[Substitution]:
    """Return a list of Substitutions given a variety of starting inputs."""
    ...

