"""
This type stub file was generated by pyright.
"""

from typing import List, Text
from ..launch_context import LaunchContext
from ..substitution import Substitution

"""Module for the perform_substitutions() utility function."""
def perform_substitutions(context: LaunchContext, subs: List[Substitution]) -> Text:
    """Resolve a list of Substitutions with a context into a single string."""
    ...

