"""
This type stub file was generated by pyright.
"""

import asyncio
import signal
from typing import Callable, Optional, Union

"""Module for signal management functionality."""
class AsyncSafeSignalManager:
    """
    A context manager class for asynchronous handling of signals.

    Similar in purpose to :func:`asyncio.loop.add_signal_handler` but
    not limited to Unix platforms.

    Signal handlers can be registered at any time with a given manager.
    These will become active for the extent of said manager context.
    Unlike regular signal handlers, asynchronous signals handlers
    can safely interact with their event loop.

    The same manager can be used multiple consecutive times and even
    be nested with other managers, as these are independent from each
    other i.e. managers do not override each other's handlers.

    If used outside of the main thread, a ValueError is raised.

    The underlying mechanism is built around :func:`signal.set_wakeup_fd`
    so as to not interfere with regular handlers installed via
    :func:`signal.signal`.
    All signals received are forwarded to the previously setup file
    descriptor, if any.

    ..warning::
        Within (potentially nested) contexts, :func:`signal.set_wakeup_fd`
        calls are intercepted such that the given file descriptor overrides
        the previously setup file descriptor for the outermost manager.
        This ensures the manager's chain of signal wakeup file descriptors
        is not broken by third-party code or by asyncio itself in some platforms.
    """
    __current: AsyncSafeSignalManager = ...
    __set_wakeup_fd: Callable[[int], int] = ...
    def __init__(self, loop: asyncio.AbstractEventLoop) -> None:
        """
        Instantiate manager.

        :param loop: event loop that will handle the signals.
        """
        ...
    
    def __enter__(self) -> AsyncSafeSignalManager:
        ...
    
    def __exit__(self, exc_type, exc_value, exc_traceback) -> None:
        ...
    
    def handle(self, signum: Union[signal.Signals, int], handler: Optional[Callable[[int], None]]) -> Optional[Callable[[int], None]]:
        """
        Register a callback for asynchronous handling of a given signal.

        :param signum: number of the signal to be handled
        :param handler: callback taking a signal number
          as its sole argument, or None
        :return: previous handler if any, otherwise None
        """
        ...
    


