"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Sequence, Text, Tuple, Type, Union
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""
This type stub file was generated by pyright.
"""
ScalarTypesTuple = ...
ListTypesTuple = ...
AllowedTypesTuple = ...
ScalarTypesType = Type[Union[int, float, bool, str]]
ListTypesType = Type[Union[List[int], List[float], List[bool], List[str]]]
AllowedTypesType = Union[ScalarTypesType, ListTypesType]
ScalarValueType = Union[int, float, bool, str]
ListValueType = Union[List[int], List[float], List[bool], List[str]]
SequenceValueType = Union[Sequence[int], Sequence[float], Sequence[bool], Sequence[str]]
AllowedValueType = Union[ScalarValueType, SequenceValueType]
SomeScalarType = Union[SomeSubstitutionsType, ScalarValueType]
SomeSequenceType = Union[(Sequence[Union[int, SomeSubstitutionsType]], Sequence[Union[float, SomeSubstitutionsType]], Sequence[Union[bool, SomeSubstitutionsType]], Sequence[Union[str, SomeSubstitutionsType]])]
SomeValueType = Union[SomeScalarType, SomeSequenceType]
NormalizedScalarType = Union[List[Substitution], ScalarValueType]
NormalizedSequenceType = Union[List[Union[int, List[Substitution]]], List[Union[float, List[Substitution]]], List[Union[bool, List[Substitution]]], List[Union[str, List[Substitution]]],]
NormalizedValueType = Union[NormalizedScalarType, NormalizedSequenceType]
StrSomeScalarType = SomeScalarType
StrSomeSequenceType = Union[(Sequence[Union[int, str]], Sequence[Union[float, str]], Sequence[Union[bool, str]], Sequence[Union[str]])]
StrSomeValueType = Union[StrSomeScalarType, StrSomeSequenceType]
def is_typing_list(data_type: Any) -> bool:
    """
    Return `True` if data_type is `typing.List` or a subscription of it.

    Examples
    --------
    .. code-block:: python

        assert is_typing_list(typing.List)
        assert is_typing_list(typing.List[int])
        assert not is_typing_list(int)

    """
    ...

def is_valid_scalar_type(data_type: AllowedTypesType) -> bool:
    """
    Return `True` if `data_type` is an instance of a valid scalar type.

    See :py:data:`ScalarTypesTuple` for further reference.
    """
    ...

def extract_type(data_type: AllowedTypesType) -> Tuple[ScalarTypesType, bool]:
    """
    Extract type information from type object.

    :param data_type: It can be:
        - a scalar type i.e. `str`, `int`, `float`, `bool`;
        - a uniform list i.e `List[str]`, `List[int]`, `List[float]`, `List[bool]`;

    :returns: a tuple (type_obj, is_list).
        `is_list` is `True` for the supported list types, if not is `False`.
        `type_obj` is the object representing that type in Python. In the case of a list,
        it's the type of the items.
        e.g.:
        `data_type = List[int]` -> `(int, True)`
        `data_type = bool` -> `(bool, False)`
    """
    ...

def is_instance_of_valid_type(value: Any, *, can_be_str: bool = ...) -> bool:
    """
    Return `True` if value is an instance of an allowed type.

    See :py:data:`AllowedTypesTuple` definition for further reference.

    :param value: variable to be checked.
    :param can_be_str: when True, non-uniform lists mixed with strings are allowed.
    :return: `True` when value is an instance of a valid type, `False` if not.
    """
    ...

def is_instance_of(value: Any, data_type: Optional[AllowedTypesType] = ..., *, can_be_str: bool = ...) -> bool:
    """
    Check if `value` is instance of `data_type`.

    :param value: variable to check.
    :param data_type: type that `value` should be an instance of.
        When `None` the function behaves like :py:func:`is_instance_of_valid_type`.
    :param can_be_str: if `True`, strings will also be accepted.
      :py:mod:`launch.frontend` makes use of this for string embedded substitutions.
    :raise: `ValueError` if `data_type` is invalid.
    :return: `True` if `value` is an instance of `data_type`, else `False`.
    """
    ...

def coerce_to_type(value: Text, data_type: Optional[AllowedTypesType] = ..., *, can_be_str: bool = ...) -> StrSomeValueType:
    """
    Coerce `value` type to `data_type`.

    :param value: string to be coerced.
    :param data_type: value will be coerced to data_type.
    :param can_be_str: if `True`, the result will be kept as an string if it cannot be coerced.
      In the case of lists, it will also accept strings as items.
      :py:mod:`launch.frontend` makes use of this for string embedded substitutions.
    :raise: `ValueError` if the coercion failed or `data_type` is invalid.
    :raise: `TypeError` if `value` is not a `str`.
    :return: `value` coerced to `data_type`.
    """
    ...

def coerce_list(value: List[Text], data_type: Optional[ScalarTypesType] = ..., *, can_be_str: bool = ...) -> StrSomeSequenceType:
    """
    Coerce a list of strings to a list of scalars.

    :param value: list of strings to be coerced.
    :param data_type: value will be coerced to data_type.
    :param can_be_str: if `True`, strings will be kept in case coercion fails.
      launch.frontend makes use of this for string embedded substitutions.
    :raise: `ValueError` if the coercion failed.
    :raise: `TypeError` if `value` is not a list of `str`.
    :return: `value` coerced to `data_type`.
    """
    ...

def get_typed_value(value: Union[Text, List[Text]], data_type: Optional[AllowedTypesType], *, can_be_str: bool = ...) -> StrSomeValueType:
    """
    Try to convert `value` to the type specified in `data_type`.

    :param value: string or list of strings to be coerced.
    :param data_type: value will be coerced to data_type.
    :param can_be_str: if `True`, strings will be kept in case coercion fails.
      In the case of lists, it will also accepts strings as items.
      launch.frontend makes use of this for string embedded substitutions.
    :raise: `ValueError` if the coercion failed.
    :raise: `TypeError` if `value` is a `list` and `data_type` is not a `typing.List[x]` object.
    :raise: `TypeError` if `value` is neither a `str` of a list of `str`.
    :return: `value` coerced to `data_type`.
    """
    ...

def is_substitution(x) -> bool:
    """
    Return `True` if `x` is some substitution.

    This can be:
    - A :py:class:`launch.Substitution` instance.
    - A list of mixed `launch.Substitution` and `str` instances,
    with at least one instance of the former.
    """
    ...

def normalize_typed_substitution(value: SomeValueType, data_type: Optional[AllowedTypesType]) -> NormalizedValueType:
    """
    Normalize a mix of substitution and values.

    This function becomes handy when you need a substitution whose result will be coerced to a
    specific type.

    Example:
    -------
    .. code-block:: python

        class MyAction(Action):
            def __init__(self, my_int: Union[int, SomeSubstitutionsType]):
                self.__my_int_normalized = normalize_typed_substitution(some_int, int)
                ...

            def execute(self, context):
                my_int = perform_typed_substitution(context, self.__my_int_normalized, int)
                ...

    List of substitutions coerced a list to strings can be confused with a single substitution
    that is coerced to a list of strings.
    e.g.: `['asd', TextSubstitution(text='bsd')]`
    To avoid confusions, the passed value will always be interpreted as a single substitution
    if possible, like in the above example (which will resolved to `'asdbsd'`).
    To make it a list of substitutions:
    `['asd', [TextSubstitution(text='bsd')]]`

    :param value: value to be normalized.
    :param data_type: `value` can be either an instance of `data_type` or a substitution.
        In the case of lists, `value` can be either a substitution or a list.
        In the later case, its items should match the type specified by `data_type` or be a
        substitution.
        If `None`, it should be possible to perform the resulting normalized `value` to a valid
        type.
        See :py:func:`is_substitution`.
    :return: the normalized `value`.
    :raise: `TypeError` if the normalized `value` cannot later be resolved to an instance
        of `data_type`, or to a valid type when `data_type is `None`.
    :raise: `ValueError` if `data_type` is not valid.
        See :py:obj:`AllowedTypesTuple`.

    """
    ...

def is_normalized_substitution(x) -> bool:
    """
    Return `True` if `x` is a normalized substitution.

    A normalized substitution is a list with :py:class:`launch.Substitution` instances as items.
    """
    ...

def perform_typed_substitution(context: LaunchContext, value: NormalizedValueType, data_type: Optional[AllowedTypesType]) -> StrSomeValueType:
    """
    Perform a normalized typed substitution.

    This function becomes handy when you need a substitution whose result will be coerced to a
    specific type.

    See :py:obj:`normalize_typed_substitution` for an example.

    :param context: A :py:class:`launch.LaunchContext` instance.
        It will be used to perform the substitutions in `value`, if there are any.
    :param value: normalized typed substitution to be performed.
    :param data_type: The return value will satisfy `is_instance_of(output) == True`.
        If after trying to coerce the performed substitution that isn't achieved,
        `ValueError` is raised.
        See :py:func:`is_instance_of`.
    :return: the result of performing all the substitutions in value and coercing the result.
    :raise: `TypeError` if the normalized `value` cannot later be resolved to an instance
        of `data_type`, or to a valid type when `data_type is `None`.
    :raise: `ValueError` if `data_type` is not valid.
        See :py:obj:`AllowedTypesTuple`.
    :raise: `ValueError` if after coercing the substitutions the end result is not of the
        expected type.
    """
    ...

