"""
This type stub file was generated by pyright.
"""

import os
import typing
from pathlib import Path

"""
This type stub file was generated by pyright.
"""
FilePath = typing.TypeVar('FilePath', str, bytes, os.PathLike, Path)
