"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import List, Tuple
from ..launch_context import LaunchContext
from ..launch_description_entity import LaunchDescriptionEntity

"""Module for the visit_all_entities_and_collect_futures() utility function."""
def visit_all_entities_and_collect_futures(entity: LaunchDescriptionEntity, context: LaunchContext) -> List[Tuple[LaunchDescriptionEntity, asyncio.Future]]:
    """
    Visit given entity, as well as all sub-entities, and collect any futures.

    Sub-entities are visited recursively and depth-first.
    The future is collected from each entity (unless it returns None) before
    continuing on to more sub-entities.

    This function may call itself to traverse the sub-entities recursively.
    """
    ...

