"""
This type stub file was generated by pyright.
"""

from typing import List
from ..launch_context import LaunchContext
from ..substitution import Substitution

"""Module for utility functions related to evaluating condition expressions."""
VALID_TRUE_EXPRESSIONS = ...
VALID_FALSE_EXPRESSIONS = ...
def evaluate_condition_expression(context: LaunchContext, expression: List[Substitution]) -> bool:
    """
    Expand an expression and then evaluate it as a condition, returning true or false.

    The expanded expression is stripped and has ``lower()`` called on it before
    being logically evaluated as either true or false.
    A string will be considered True if it matches 'true' or '1'.
    A string will be considered False if it matches 'false' or '0'.
    Any other string content (including empty string) will result in an error.

    :raises: InvalidConditionExpressionError
    """
    ...

