"""
This type stub file was generated by pyright.
"""

from typing import Text
from ..condition import Condition
from ..some_substitutions_type import SomeSubstitutionsType

"""Module for IfCondition class."""
class IfCondition(Condition):
    """
    Encapsulates an if condition to be evaluated when launching.

    This condition takes a string expression that is lexically evaluated as a
    boolean, but the expression may consist of :py:class:`launch.Substitution`
    instances.

    See :py:func:`evaluate_condition_expression` to understand what constitutes
    a valid condition expression.
    """
    def __init__(self, predicate_expression: SomeSubstitutionsType) -> None:
        ...
    
    def describe(self) -> Text:
        """Return a description of this Condition."""
        ...
    


