"""
This type stub file was generated by pyright.
"""

from typing import List
from ..substitution import Substitution

"""Module for InvalidConditionExpressionError class."""
class InvalidConditionExpressionError(ValueError):
    """Raised when an expression being evaluated as a condition is invalid."""
    def __init__(self, expression: str, unexpanded_expression: List[Substitution], valid_expressions: List[str]) -> None:
        ...
    


