"""
This type stub file was generated by pyright.
"""

from typing import Optional, Text
from ..condition import Condition
from ..some_substitutions_type import SomeSubstitutionsType

"""Module for LaunchConfigurationEquals class."""
class LaunchConfigurationEquals(Condition):
    """
    Condition on the value of a launch configuration.

    This condition takes an optional string expression that is compared with the value of
    a launch configuration.
    If the value is equal to the launch configuration value, then this ``Condition``
    evaluates to ``True``.
    The expression may consist of :py:class:`launch.Substitution` instances.

    If ``None`` is provided instead of a string expression, then the condition
    evaluates to ``True`` if the launch configuration is not set.

    .. deprecated:: 1.1.0
       Replaced by the more universally usable substitutions:
       'EqualsSubstitution' and 'NotEqualsSubstitution'
    """
    def __init__(self, launch_configuration_name: Text, expected_value: Optional[SomeSubstitutionsType]) -> None:
        ...
    
    def describe(self) -> Text:
        """Return a description of this Condition."""
        ...
    


