"""
This type stub file was generated by pyright.
"""

from typing import Text
from .if_condition import IfCondition
from ..some_substitutions_type import SomeSubstitutionsType

"""Module for UnlessCondition class."""
class UnlessCondition(IfCondition):
    """
    Encapsulates an if condition to be evaluated when launching.

    Exactly the same as :py:class:`IfCondition` except it returns true if the
    condition expression evaluates to false.
    """
    def __init__(self, predicate_expression: SomeSubstitutionsType) -> None:
        ...
    
    def describe(self) -> Text:
        """Return a description of this Condition."""
        ...
    


