"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Optional, Text, Tuple
from .condition import Condition
from .launch_context import LaunchContext
from .launch_description_entity import LaunchDescriptionEntity

"""
This type stub file was generated by pyright.
"""
if False:
    ...
class Action(LaunchDescriptionEntity):
    """
    LaunchDescriptionEntity that represents a user intention to do something.

    The action describes the intention to do something, but also can be
    executed given a :class:`launch.LaunchContext` at runtime.
    """
    def __init__(self, *, condition: Optional[Condition] = ...) -> None:
        """
        Create an Action.

        If the conditions argument is not None, the condition object will be
        evaluated while being visited and the action will only be executed if
        the condition evaluates to True.

        :param condition: Either a :py:class:`Condition` or None
        """
        ...
    
    @staticmethod
    def parse(entity: Entity, parser: Parser) -> tuple[type[Action], Dict[str, Condition]]:
        """
        Return the `Action` action and kwargs for constructing it.

        This is only intended for code reuse.
        This class is not exposed with `expose_action`.
        """
        ...
    
    @property
    def condition(self) -> Optional[Condition]:
        """Getter for condition."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this Action."""
        ...
    
    def get_sub_entities(self) -> List[LaunchDescriptionEntity]:
        """Return subentities."""
        ...
    
    def describe_sub_entities(self) -> List[LaunchDescriptionEntity]:
        """Override describe_sub_entities from LaunchDescriptionEntity."""
        ...
    
    def describe_conditional_sub_entities(self) -> List[Tuple[Text, Iterable[LaunchDescriptionEntity],]]:
        """Override describe_conditional_sub_entities from LaunchDescriptionEntity."""
        ...
    
    def visit(self, context: LaunchContext) -> Optional[List[LaunchDescriptionEntity]]:
        """Override visit from LaunchDescriptionEntity so that it executes."""
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[LaunchDescriptionEntity]]:
        """
        Execute the action.

        Should be overridden by derived class, but by default does nothing.
        """
        ...
    


