"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, Text
from .launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
class Condition:
    """
    Encapsulates a condition to be evaluated when launching.

    The given predicate receives a launch context and is evaluated while
    launching, but must return True or False.

    If a predicate is not set when evaluated, False is returned.
    """
    def __init__(self, *, predicate: Optional[Callable[[LaunchContext], bool]] = ...) -> None:
        ...
    
    def describe(self) -> Text:
        """Return a description of this Condition."""
        ...
    
    def evaluate(self, context: LaunchContext) -> bool:
        """Evaluate the condition."""
        ...
    


