"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional, TYPE_CHECKING, Text, Tuple
from .event import Event
from .some_entities_type import SomeEntitiesType
from .launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class BaseEventHandler:
    """
    Base class for event handlers, which handle events in the launch system.

    Entities yielded by the event handler can access the event being handled
    via the context's locals, e.g. `context.locals.event`
    As another example, getting the name of the event as a Substitution:
    `launch.substitutions.LocalSubstitution('event.name')`.
    """
    def __init__(self, *, matcher: Callable[[Event], bool], handle_once: bool = ...) -> None:
        """
        Create a BaseEventHandler.

        :param: matcher is a callable that takes an event and returns True if
            the event should be handled by this event handler, False otherwise.
        :param: handle_once is a flag that, if True, unregisters this EventHandler
            after being handled once.
        """
        ...
    
    @property
    def handle_once(self) -> bool:
        """Getter for handle_once flag."""
        ...
    
    @property
    def handler_description(self) -> None:
        """
        Return the string description of the handler.

        This should be overridden.
        """
        ...
    
    @property
    def matcher_description(self) -> None:
        """
        Return the string description of the matcher.

        This should be overridden.
        """
        ...
    
    def matches(self, event: Event) -> bool:
        """Return True if the given event should be handled by this event handler."""
        ...
    
    def describe(self) -> Tuple[Text, List[SomeEntitiesType]]:
        """Return the description list with 0 as a string, and then LaunchDescriptionEntity's."""
        ...
    
    def handle(self, event: Event, context: LaunchContext) -> Optional[SomeEntitiesType]:
        """
        Handle the given event.

        This implementation should always be called by child classes in order to properly
        support common event handler functionality.
        """
        ...
    


class EventHandler(BaseEventHandler):
    def __init__(self, *, matcher: Callable[[Event], bool], entities: Optional[SomeEntitiesType] = ..., handle_once: bool = ...) -> None:
        """
        Create an EventHandler.

        :param: matcher is a callable that takes an event and returns True if
            the event should be handled by this event handler, False otherwise.
        :param: entities is an LaunchDescriptionEntity or list of them, and is
            returned by handle() unconditionally if matcher returns True.
        :param: handle_once is a flag that, if True, unregisters this EventHandler
            after being handled once.
        """
        ...
    
    @property
    def entities(self) -> SomeEntitiesType | None:
        """Getter for entities."""
        ...
    
    def describe(self) -> Tuple[Text, List[SomeEntitiesType]]:
        """Return the description list with 0 as a string, and then LaunchDescriptionEntity's."""
        ...
    
    def handle(self, event: Event, context: LaunchContext) -> Optional[SomeEntitiesType]:
        """Handle the given event."""
        ...
    


