"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class Event:
    """Event that can be emitted during runtime of a launched system."""
    name = ...


