"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class InvalidLaunchFileError(Exception):
    """Exception raised when the given launch file is not valid."""
    def __init__(self, extension=..., *, likely_errors=...) -> None:
        """Create an InvalidLaunchFileError."""
        ...
    
    def __str__(self) -> str:
        """Pretty print."""
        ...
    


