"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Optional, TYPE_CHECKING, Text, Tuple
from .action import Action
from .actions import DeclareLaunchArgument
from .launch_context import LaunchContext
from .launch_description_entity import LaunchDescriptionEntity
from .actions.include_launch_description import IncludeLaunchDescription

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class LaunchDescription(LaunchDescriptionEntity):
    """
    Description of a launch-able system.

    The description is expressed by a collection of entities which represent
    the system architect's intentions.

    The description may also have arguments, which are declared by
    :py:class:`launch.actions.DeclareLaunchArgument` actions within this
    launch description.

    Arguments for this description may be accessed via the
    :py:meth:`get_launch_arguments` method.
    The arguments are gathered by searching through the entities in this
    launch description and the descriptions of each entity (which may include
    entities yielded by those entities).
    """
    def __init__(self, initial_entities: Optional[Iterable[LaunchDescriptionEntity]] = ..., *, deprecated_reason: Optional[Text] = ...) -> None:
        """Create a LaunchDescription."""
        ...
    
    def visit(self, context: LaunchContext) -> Optional[List[LaunchDescriptionEntity]]:
        """Override visit from LaunchDescriptionEntity to visit contained entities."""
        ...
    
    def describe_sub_entities(self) -> List[LaunchDescriptionEntity]:
        """Override describe_sub_entities from LaunchDescriptionEntity to return sub entities."""
        ...
    
    def get_launch_arguments(self, conditional_inclusion=...) -> List[DeclareLaunchArgument]:
        """
        Return a list of :py:class:`launch.actions.DeclareLaunchArgument` actions.

        See :py:meth:`get_launch_arguments_with_include_launch_description_actions()`
        for more details.
        """
        ...
    
    def get_launch_arguments_with_include_launch_description_actions(self, conditional_inclusion=...) -> List[Tuple[DeclareLaunchArgument, List[IncludeLaunchDescription]]]:
        """
        Return a list of launch arguments with its associated include launch descriptions actions.

        The first element of the tuple is a declare launch argument action.
        The second is `None` if the argument was declared at the top level of this
        launch description, if not it's a list with all the nested include launch description
        actions involved.

        This list is generated (never cached) by searching through this launch
        description for any instances of the action that declares launch
        arguments.

        It will use :py:meth:`launch.LaunchDescriptionEntity.describe_sub_entities`
        and :py:meth:`launch.LaunchDescriptionEntity.describe_conditional_sub_entities`
        in order to discover as many instances of the declare launch argument
        actions as is possible.
        Also, specifically in the case of the
        :py:class:`launch.actions.IncludeLaunchDescription` action, the method
        :py:meth:`launch.LaunchDescriptionSource.try_get_launch_description_without_context`
        is used to attempt to load launch descriptions without the "runtime"
        context available.
        This function may fail, e.g. if the path to the launch file to include
        uses the values of launch configurations that have not been set yet,
        and in that case the failure is ignored and the arguments defined in
        those launch files will not be seen either.

        Duplicate declarations of an argument are ignored, therefore the
        default value and description from the first instance of the argument
        declaration is used.
        """
        ...
    
    @property
    def entities(self) -> List[LaunchDescriptionEntity]:
        """Getter for the entities."""
        ...
    
    def add_entity(self, entity: LaunchDescriptionEntity) -> None:
        """Add an entity to the LaunchDescription."""
        ...
    
    def add_action(self, action: Action) -> None:
        """Add an action to the LaunchDescription."""
        ...
    
    @property
    def deprecated(self) -> bool:
        """Getter for deprecated."""
        ...
    
    @property
    def deprecated_reason(self) -> Optional[Text]:
        """
        Getter for deprecated.

        Returns `None` if the launch description is not deprecated.
        """
        ...
    


