"""
This type stub file was generated by pyright.
"""

from typing import Optional
from .launch_context import LaunchContext
from .launch_description import LaunchDescription
from .some_substitutions_type import SomeSubstitutionsType

"""
This type stub file was generated by pyright.
"""
class LaunchDescriptionSource:
    """Encapsulation of a launch description, where it comes from, and how it was generated."""
    def __init__(self, launch_description: Optional[LaunchDescription] = ..., location: SomeSubstitutionsType = ..., method: str = ...) -> None:
        """
        Create a LaunchDescriptionSource.

        For example, loading a file called ``example.launch.py`` for inclusion
        might end up setting `location` to ``/path/to/example.launch.py`` and
        the ``method`` to be ``interpreted python launch file``.

        :param launch_description: the launch description that this source represents
        :param location: the location from where this launch description was loaded if applicable
        :param method: the method by which the launch description was generated
        """
        ...
    
    def try_get_launch_description_without_context(self) -> Optional[LaunchDescription]:
        """
        Attempt to load the LaunchDescription without a context, return None if unsuccessful.

        This method is useful for trying to introspect the included launch
        description without visiting the user of this source.
        """
        ...
    
    def get_launch_description(self, context: LaunchContext) -> LaunchDescription:
        """Get the LaunchDescription, loading it if necessary."""
        ...
    
    @property
    def location(self) -> str:
        """
        Get the location of the launch description source as a string.

        The string is either a list of Substitution instances converted to
        strings or the expanded path if :py:meth:`get_launch_description` has
        been called.
        """
        ...
    
    @property
    def method(self) -> str:
        """Getter for self.__method."""
        ...
    


