"""
This type stub file was generated by pyright.
"""

from typing import Coroutine, Iterable, Optional, Text
from .event import Event
from .launch_description import LaunchDescription

"""Module for the LaunchService class."""
class LaunchService:
    """Service that manages the event loop and runtime for launched system."""
    def __init__(self, *, argv: Optional[Iterable[Text]] = ..., noninteractive: bool = ..., debug: bool = ...) -> None:
        """
        Create a LaunchService.

        :param: argv stored in the context for access by the entities, None results in []
        :param: noninteractive if True (not default), this service will assume it has
            no terminal associated e.g. it is being executed from a non interactive script
        :param: debug if True (not default), asyncio and the logger are set up for debug
        """
        ...
    
    def emit_event(self, event: Event) -> None:
        """
        Emit an event synchronously and thread-safely.

        If the LaunchService is not running, the event is queued until it is.
        """
        ...
    
    def include_launch_description(self, launch_description: LaunchDescription) -> None:
        """
        Evaluate a given LaunchDescription and visits all of its entities.

        This method is thread-safe.
        """
        ...
    
    async def run_async(self, *, shutdown_when_idle=...) -> int:
        """
        Visit all entities of all included LaunchDescription instances asynchronously.

        This should only ever be run from the main thread and not concurrently with other
        asynchronous runs.

        :param: shutdown_when_idle if True (default), the service will shutdown when idle.
        :return: the return code (non-zero if there are any errors)
        """
        ...
    
    def run(self, *, shutdown_when_idle=...) -> int:
        """
        Run an event loop and visit all entities of all included LaunchDescription instances.

        This should only ever be run from the main thread and not concurrently with
        asynchronous runs (see `run_async()` documentation).

        Note that KeyboardInterrupt is caught and ignored, as signals are handled separately.
        After the run ends, this behavior is undone.

        :param: shutdown_when_idle if True (default), the service will shutdown when idle
        :return: the return code (non-zero if there are any errors)
        """
        ...
    
    def shutdown(self, force_sync=...) -> Optional[Coroutine]:
        """
        Shutdown all on-going activities and then stop the asyncio run loop.

        This will cause the running LaunchService to eventually exit.

        Does nothing if the LaunchService is not running.

        This will return an awaitable coroutine if called from within the loop.

        This method is thread-safe.
        """
        ...
    
    @property
    def context(self) -> LaunchContext:
        """Getter for context."""
        ...
    
    @property
    def event_loop(self) -> None:
        """Getter for the event loop being used in the thread running the launch service."""
        ...
    
    @property
    def task(self) -> Task[Any] | None:
        """Return asyncio task associated with this launch service."""
        ...
    


