"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Text
from .action import Action
from .event_handler import BaseEventHandler
from .launch_description import LaunchDescription
from .launch_description_entity import LaunchDescriptionEntity
from .some_substitutions_type import SomeSubstitutionsType

"""Module for the LaunchIntrospector class."""
def indent(lines: List[Text], indention: Text = ...) -> List[Text]:
    """Indent a list of strings and return them."""
    ...

def tree_like_indent(lines: List[Text]) -> List[Text]:
    """Replace whitespace with "tree"-like indentation symbols."""
    ...

def format_entities(entities: Iterable[LaunchDescriptionEntity]) -> List[Text]:
    """Return a list of lines of text that represent of a list of LaunchDescriptionEntity's."""
    ...

def format_substitutions(substitutions: SomeSubstitutionsType) -> Text:
    """Return a text representation of some set of substitutions."""
    ...

def format_event_handler(event_handler: BaseEventHandler) -> List[Text]:
    """Return a text representation of an event handler."""
    ...

def format_action(action: Action) -> List[Text]:
    """Return a text representation of an action."""
    ...

class LaunchIntrospector:
    """Provides an interface through which you can visit all entities of a LaunchDescription."""
    def format_launch_description(self, launch_description: LaunchDescription) -> Text:
        """Return a string representation of a LaunchDescription."""
        ...
    


