"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any, Dict, Iterable, MutableMapping, Optional, Text
from .event import Event
from .event_handler import BaseEventHandler
from .substitution import Substitution

"""
This type stub file was generated by pyright.
"""
class LaunchContext:
    """Runtime context used by various launch entities when being visited or executed."""
    def __init__(self, *, argv: Optional[Iterable[Text]] = ..., noninteractive: bool = ...) -> None:
        """
        Create a LaunchContext.

        :param: argv stored in the context for access by the entities, None results in []
        :param: noninteractive if True (not default), this service will assume it has
            no terminal associated e.g. it is being executed from a non interactive script
        """
        ...
    
    @property
    def argv(self) -> Iterable[Text] | list[Any]:
        """Getter for argv."""
        ...
    
    @property
    def noninteractive(self) -> bool:
        """Getter for noninteractive."""
        ...
    
    @property
    def is_shutdown(self) -> bool:
        """Getter for is_shutdown."""
        ...
    
    @property
    def asyncio_loop(self) -> AbstractEventLoop | None:
        """Getter for asyncio_loop."""
        ...
    
    def add_completion_future(self, completion_future: asyncio.Future) -> None:
        """Add an asyncio.Future to the list of futures that the LaunchService will wait on."""
        ...
    
    def extend_globals(self, extensions: Dict[Text, Any]) -> None:
        """
        Extend the context.locals object permanently with new members.

        These "globals" are in the context.locals, but are overridden by
        overlapping keys provided by extend_locals().
        """
        ...
    
    def extend_locals(self, extensions: Dict[Text, Any]) -> None:
        """Extend the context.locals object with new members until popped."""
        ...
    
    def get_locals_as_dict(self) -> Dict[Text, Any]:
        """Access the context locals as a dictionary."""
        ...
    
    @property
    def locals(self) -> AttributeDict:
        """Getter for the locals."""
        class AttributeDict:
            ...
        
        
    
    @property
    def launch_configurations(self) -> Dict[Text, Any]:
        """Getter for launch_configurations dictionary."""
        ...
    
    @property
    def environment(self) -> MutableMapping[Text, Text]:
        """Getter for environment variables dictionary."""
        ...
    
    def would_handle_event(self, event: Event) -> bool:
        """Check whether an event would be handled or not."""
        ...
    
    def register_event_handler(self, event_handler: BaseEventHandler, append=...) -> None:
        """
        Register a event handler.

        :param append: if 'true', the new event handler will be executed after the previously
            registered ones. If not, it will prepend the old handlers.
        """
        ...
    
    def unregister_event_handler(self, event_handler: BaseEventHandler) -> None:
        """Unregister an event handler."""
        ...
    
    def emit_event_sync(self, event: Event) -> None:
        """Emit an event synchronously."""
        ...
    
    async def emit_event(self, event: Event) -> None:
        """Emit an event."""
        ...
    
    def perform_substitution(self, substitution: Substitution) -> Text:
        """Perform substitution on given Substitution."""
        ...
    


