"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Union
from .launch_description_entity import LaunchDescriptionEntity

"""
This type stub file was generated by pyright.
"""
SomeEntitiesType = Union[LaunchDescriptionEntity, Iterable[LaunchDescriptionEntity],]
SomeEntitiesType_types_tuple = ...
