"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Iterable, Text, Union
from .substitution import Substitution

"""
This type stub file was generated by pyright.
"""
SomeSubstitutionsType = Union[Text, Path, Substitution, Iterable[Union[Text, Path, Substitution]],]
SomeSubstitutionsType_types_tuple = ...
