"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Text
from .launch_context import LaunchContext

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class Substitution:
    """Encapsulates a substitution to be performed at runtime."""
    def describe(self) -> Text:
        """
        Return a description of this substitution as a string.

        When inherited from, calling this base class's default method is not
        required.
        """
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """
        Perform the substitution, given the launch context, and return it as a string.

        This should be overridden by the derived classes, and the default
        raises NotImplementedError.

        :raises: NotImplementedError
        """
        ...
    


