"""
This type stub file was generated by pyright.
"""

from ..launch_description_source import LaunchDescriptionSource
from ..some_substitutions_type import SomeSubstitutionsType

"""Module for the AnyLaunchDescriptionSource class."""
class AnyLaunchDescriptionSource(LaunchDescriptionSource):
    """
    Encapsulation of a launch file, which can be loaded during launch.

    This launch description source will attempt to load a launch file based on its extension
    first, then it will try to load the file as a python launch file, and then as a declarative
    (markup based) launch file.
    It is recommended to use specific `LaunchDescriptionSource` subclasses when possible.
    """
    def __init__(self, launch_file_path: SomeSubstitutionsType) -> None:
        """
        Create an AnyLaunchDescriptionSource.

        If a relative path is passed, it will be relative to the current working
        directory wherever the launch file was run from.

        :param launch_file_path: the path to the launch file. It can be made up of Substitution
            instances which are expanded when :py:meth:`get_launch_description()` is called.
        """
        ...
    


