"""
This type stub file was generated by pyright.
"""

from typing import Text, Type
from ..frontend import Parser
from ..launch_description import LaunchDescription

"""Python package utility functions related to loading Frontend Launch Files."""
def get_launch_description_from_any_launch_file(launch_file_path: Text, *, parser: Type[Parser] = ...) -> LaunchDescription:
    """
    Load a given launch file (by path), and return the launch description from it.

    :raises `launch.invalid_launch_file_error.InvalidLaunchFileError`: Failed to load launch file.
        It's only showed with launch files without extension (or not recognized extensions).
    :raises `SyntaxError`: Invalid file. The file may have a syntax error in it.
    :raises `ValueError`: Invalid file. The file may not be a text file.
    """
    ...

