"""
This type stub file was generated by pyright.
"""

from typing import Type
from ..frontend import Parser
from ..launch_description_source import LaunchDescriptionSource
from ..some_substitutions_type import SomeSubstitutionsType

"""Module for the FrontendLaunchDescriptionSource class."""
class FrontendLaunchDescriptionSource(LaunchDescriptionSource):
    """
    Encapsulation of a declarative (markup based) launch file.

    It can be loaded during launch using an `IncludeLaunchDescription` action.
    """
    def __init__(self, launch_file_path: SomeSubstitutionsType, *, method: str = ..., parser: Type[Parser] = ...) -> None:
        """
        Create a FrontendLaunchDescriptionSource.

        The given file path should be to a launch frontend style file (like xml or yaml).
        If a relative path is passed, it will be relative to the current working
        directory wherever the launch file was run from.

        :param launch_file_path: the path to the launch file. It can be made up of Substitution
            instances which are expanded when :py:meth:`get_launch_description()` is called.
        :param parser: an specific parser implementation
        """
        ...
    


