"""
This type stub file was generated by pyright.
"""

from typing import Text, Type
from ..frontend import InvalidFrontendLaunchFileError, Parser
from ..launch_description import LaunchDescription

"""Python package utility functions related to loading Frontend Launch Files."""
InvalidFrontendLaunchFileError = ...
def get_launch_description_from_frontend_launch_file(frontend_launch_file_path: Text, *, parser: Type[Parser] = ...) -> LaunchDescription:
    """Load a `LaunchDescription` from a declarative (markup based) launch file."""
    ...

