"""
This type stub file was generated by pyright.
"""

from typing import Callable, Text
from ..event import Event

"""Module for event_named() function."""
def event_named(name: Text) -> Callable[[Event], bool]:
    """Generate a lambda that compares the given name to an event's name given to the lambda."""
    ...

