"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional, TYPE_CHECKING, Text, Tuple, Type, Union
from ..event import Event
from ..event_handler import BaseEventHandler
from ..launch_context import LaunchContext
from ..some_entities_type import SomeEntitiesType
from ..action import Action

"""Module for OnActionEventBase class."""
if TYPE_CHECKING:
    ...
class OnActionEventBase(BaseEventHandler):
    """Base event handler for events that have a source action."""
    def __init__(self, *, action_matcher: Optional[Union[Callable[[Action], bool], Action]], on_event: Union[SomeEntitiesType, Callable[[Event, LaunchContext], Optional[SomeEntitiesType]]], target_event_cls: Type[Event], target_action_cls: Type[Action], **kwargs) -> None:
        """
        Construct a `OnActionEventBase` instance.

        :param action_matcher: `ExecuteProcess` instance or callable to filter events
            from which process/processes to handle.
        :param on_event: Action to be done to handle the event.
        :param target_event_cls: A subclass of `Event`, indicating which events
            should be handled.
        :param target_action_cls: A subclass of `Action`, indicating which kind of action can
            generate the event.
        """
        ...
    
    def handle(self, event: Event, context: LaunchContext) -> Optional[SomeEntitiesType]:
        """Handle the given event."""
        ...
    
    def describe(self) -> Tuple[Text, List[SomeEntitiesType]]:
        """Return a description tuple."""
        ...
    
    @property
    def handler_description(self) -> Text:
        """Return the string description of the handler."""
        ...
    
    @property
    def matcher_description(self) -> Text:
        """Return the string description of the matcher."""
        ...
    


