"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, TYPE_CHECKING, Union
from .on_action_event_base import OnActionEventBase
from ..events import ExecutionComplete
from ..launch_context import LaunchContext
from ..some_entities_type import SomeEntitiesType
from .. import Action

if TYPE_CHECKING:
    ...
class OnExecutionComplete(OnActionEventBase):
    """
    Convenience class for handling an action completion event.

    It may be configured to only handle the completion of a specific action,
    or to handle them all.
    """
    def __init__(self, *, target_action: Optional[Union[Callable[[Action], bool], Action]] = ..., on_completion: Union[SomeEntitiesType, Callable[[ExecutionComplete, LaunchContext], Optional[SomeEntitiesType]]], **kwargs) -> None:
        """Create an OnExecutionComplete event handler."""
        ...
    


