"""
This type stub file was generated by pyright.
"""

from typing import Text
from ..event_handler import EventHandler

"""Module for OnIncludeLaunchDescription class."""
class OnIncludeLaunchDescription(EventHandler):
    """Event handler used to handle asynchronous requests to include LaunchDescriptions."""
    def __init__(self, **kwargs) -> None:
        """Create an OnIncludeLaunchDescription event handler."""
        ...
    
    @property
    def handler_description(self) -> Text:
        """Return the string description of the handler."""
        ...
    
    @property
    def matcher_description(self) -> Text:
        """Return the string description of the matcher."""
        ...
    


