"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, TYPE_CHECKING, Union
from .on_action_event_base import OnActionEventBase
from ..events.process import ProcessExited
from ..launch_context import LaunchContext
from ..some_entities_type import SomeEntitiesType
from ..actions import ExecuteLocal

"""Module for OnProcessExit class."""
if TYPE_CHECKING:
    ...
class OnProcessExit(OnActionEventBase):
    """
    Convenience class for handling a process exited event.

    It may be configured to only handle the exiting of a specific action,
    or to handle all exited processes.
    """
    def __init__(self, *, target_action: Optional[Union[Callable[[ExecuteLocal], bool], ExecuteLocal]] = ..., on_exit: Union[SomeEntitiesType, Callable[[ProcessExited, LaunchContext], Optional[SomeEntitiesType]]], **kwargs) -> None:
        """Create an OnProcessExit event handler."""
        ...
    


