"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, TYPE_CHECKING, Union
from .on_action_event_base import OnActionEventBase
from ..events.process import ProcessIO
from ..some_entities_type import SomeEntitiesType
from ..action import Action

"""Module for OnProcessIO class."""
if TYPE_CHECKING:
    ...
class OnProcessIO(OnActionEventBase):
    """Convenience class for handling I/O from processes via events."""
    def __init__(self, *, target_action: Optional[Union[Callable[[Action], bool], Action]] = ..., on_stdin: Optional[Callable[[ProcessIO], Optional[SomeEntitiesType]]] = ..., on_stdout: Optional[Callable[[ProcessIO], Optional[SomeEntitiesType]]] = ..., on_stderr: Optional[Callable[[ProcessIO], Optional[SomeEntitiesType]]] = ..., **kwargs) -> None:
        """Create an OnProcessIO event handler."""
        ...
    


