"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, TYPE_CHECKING, Union
from .on_action_event_base import OnActionEventBase
from ..events.process import ProcessStarted
from ..launch_context import LaunchContext
from ..some_entities_type import SomeEntitiesType
from ..action import Action

"""Module for OnProcessStart class."""
if TYPE_CHECKING:
    ...
class OnProcessStart(OnActionEventBase):
    """
    Convenience class for handling a process started event.

    It may be configured to only handle the starting of a specific action,
    or to handle all started processes.
    """
    def __init__(self, *, target_action: Optional[Union[Callable[[Action], bool], Action]] = ..., on_start: Union[SomeEntitiesType, Callable[[ProcessStarted, LaunchContext], Optional[SomeEntitiesType]]], **kwargs) -> None:
        """Create an OnProcessStart event handler."""
        ...
    


