"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, TYPE_CHECKING, Text, Union
from ..event import Event
from ..event_handler import BaseEventHandler
from ..events import Shutdown
from ..some_entities_type import SomeEntitiesType
from ..launch_context import LaunchContext

"""Module for OnShutdown class."""
if TYPE_CHECKING:
    ...
def gen_handler(entities: SomeEntitiesType) -> Callable[[Shutdown, LaunchContext], SomeEntitiesType]:
    ...

class OnShutdown(BaseEventHandler):
    """Convenience class for handling the launch shutdown event."""
    def __init__(self, *, on_shutdown: Union[SomeEntitiesType, Callable[[Shutdown, LaunchContext], Optional[SomeEntitiesType]]], **kwargs) -> None:
        """Create an OnShutdown event handler."""
        ...
    
    def handle(self, event: Event, context: LaunchContext) -> Optional[SomeEntitiesType]:
        """Handle the given event."""
        ...
    
    @property
    def handler_description(self) -> Text:
        """Return the string description of the handler."""
        ...
    
    @property
    def matcher_description(self) -> Literal['event issubclass of launch.events.Shutdown']:
        """Return the string description of the matcher."""
        ...
    


