"""
This type stub file was generated by pyright.
"""

from ..action import Action
from ..event import Event

"""Module for ExecutionComplete event."""
class ExecutionComplete(Event):
    """Event that is emitted on action execution completion."""
    name = ...
    def __init__(self, *, action: Action) -> None:
        """Create an ExecutionComplete event."""
        ...
    
    @property
    def action(self) -> Action:
        """Getter for action."""
        ...
    


