"""
This type stub file was generated by pyright.
"""

from ..event import Event
from ..launch_description import LaunchDescription

"""Module for IncludeLaunchDescription event."""
class IncludeLaunchDescription(Event):
    """Event that can be emitted to cause a LaunchDescription to be included."""
    name = ...
    def __init__(self, launch_description: LaunchDescription) -> None:
        """Create an IncludeLaunchDescription event."""
        ...
    
    @property
    def launch_description(self) -> LaunchDescription:
        """Getter for launch_description."""
        ...
    


