"""
This type stub file was generated by pyright.
"""

from typing import Callable
from ..action import Action

"""Module for standard "matchers", which are used with Events."""
def matches_action(target_action: Action) -> Callable[[Action], bool]:
    """Return a matcher which matches based on an exact given ExecuteProcess action."""
    ...

