"""
This type stub file was generated by pyright.
"""

from typing import Text
from ..event import Event

"""Module for Shutdown event."""
class Shutdown(Event):
    """Event that is emitted on shutdown of a launched system."""
    name = ...
    def __init__(self, *, reason: Text = ..., due_to_sigint: bool = ...) -> None:
        """Create a Shutdown event."""
        ...
    
    @property
    def reason(self) -> Text:
        """Getter for reason."""
        ...
    
    @property
    def due_to_sigint(self) -> bool:
        """Getter for due_to_sigint."""
        ...
    


