"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ..event import Event
from ..actions import TimerAction

"""Module for TimerEvent event."""
if TYPE_CHECKING:
    ...
class TimerEvent(Event):
    """Event that fires when a TimerAction's period expires."""
    name = ...
    def __init__(self, *, timer_action: TimerAction) -> None:
        """Create a TimerEvent."""
        ...
    
    @property
    def timer_action(self) -> TimerAction:
        """Getter for timer_action."""
        ...
    


