"""
This type stub file was generated by pyright.
"""

import codecs
import datetime
import locale
import logging
import logging.handlers
import os
import socket
import sys
from typing import Any, List
from . import handlers

"""Module for the launch specific logging."""
__all__ = ['get_logger', 'get_output_loggers', 'handlers', 'launch_config', 'reset']
class LaunchConfig:
    """Launch Logging Configuration class."""
    def __init__(self) -> None:
        ...
    
    def reset(self) -> None:
        ...
    
    @property
    def level(self) -> int:
        ...
    
    @level.setter
    def level(self, new_level) -> None:
        """
        Set up launch logging verbosity level for all loggers.

        :param new_level: the default log level used for all loggers.
        """
        ...
    
    @property
    def log_dir(self) -> str:
        """Get the current log directory, generating it if necessary."""
        ...
    
    @log_dir.setter
    def log_dir(self, new_log_dir) -> None:
        """
        Set up launch logging directory.

        :param new_log_dir: used as base path for all log file collections.
        """
        ...
    
    @property
    def log_handler_factory(self):
        """Get the log_handler_factory, generating it if necessary."""
        ...
    
    @log_handler_factory.setter
    def log_handler_factory(self, new_log_handler_factory) -> None:
        """
        Set up log handler factory.

        :param new_log_handler_factory: a callable to build log file handler.
           It takes a path to the log file and it must return a `logging.Handler`
           variant with per logger formatting support.
           See `launch.logging.handlers` module for further reference and easy reuse
           of existing standard `logging.handlers` module handlers.
           Defaults to regular log file handlers for logging if no factory is given.
        """
        ...
    
    def set_screen_format(self, screen_format, *, screen_style=...) -> None:
        """
        Set up screen formats.

        For the ``screen_format`` argument there are a few aliases:

          - 'default' to log verbosity level, logger name and logged message
          - 'default_with_timestamp' to add timestamps to the 'default' format

        :param screen_format: format specification used when logging to the screen,
            as expected by the `logging.Formatter` constructor.
            Alternatively, aliases for common formats are available, see above.
            This format can also be overridden by the environment variable
            'OVERRIDE_LAUNCH_SCREEN_FORMAT'.
        :param screen_style: the screen style used if no alias is used for
            screen_format.
            No style can be provided if a format alias is given.
        """
        ...
    
    def get_screen_handler(self):
        """
        Get the one and only screen logging handler.

        See launch_config() documentation for screen logging configuration.
        """
        ...
    
    def set_log_format(self, log_format, *, log_style=...) -> None:
        """
        Set up launch log file format.

        :param log_format: the format used when logging to the main launch log file,
            as expected by the `logging.Formatter` constructor.
            Alternatively, the 'default' alias can be given to log verbosity level,
            logger name and logged message.
            This format can also be overridden by the environment variable
            'OVERRIDE_LAUNCH_LOG_FORMAT'.
        :param log_style: the log style used if no alias is given for log_format.
            No style can be provided if a format alias is given.
        """
        ...
    
    def get_log_file_path(self, file_name=...) -> str:
        """
        Get the absolute path to the given log file.

        :param: file_name of the log file from which to get the absolute path.
        :return: the absolute path to the log file.
        """
        ...
    
    def get_log_file_handler(self, file_name=...):
        """
        Get the logging handler to a log file.

        See launch_config() documentation for application wide log file
        logging configuration.

        :param: file_name of the log file whose handler is to be retrieved.
        :return: the logging handler associated to the file (always the same
        once constructed).
        """
        ...
    


launch_config = ...
def log_launch_config(*, logger=...) -> None:
    """Log logging configuration details relevant for a user with the given logger."""
    ...

def get_logger(name=...) -> logging.Logger:
    """Get named logger, configured to output to screen and launch main log file."""
    ...

def get_output_loggers(process_name, output_config) -> tuple[Logger, Logger]:
    """
    Get the stdout and stderr output loggers for the given process name.

    The output_config may be a dictionary with one or more of the optional keys
    'stdout', 'stderr', or 'both' (stdout and stderr combined) which represent
    the various process output sources, and values for those keys to assign one
    or more logging destinations to the source.
    The logging destination values may be:

      - 'screen': log it to the screen,
      - 'log': log it to launch log file, or
      - 'own_log': log it to a separate log file.

    When logging the stdout and stderr separately, the log file names follow
    the ``<process_name>-<source>.log`` pattern where ``<source>`` is either
    'stdout' or 'stderr'
    When the 'both' logging destination is used the log file name follows the
    ``<process_name>.log`` pattern.

    The "launch log file" is a log file which is create for each run of
    the launch.LaunchService, and at least captures the log output from launch
    itself, but may also include output from subprocess's if configured so.

    Alternatively, the output_config parameter may be a string which represents
    one of a couple available aliases for common logging configurations.
    The available aliases are:

      - 'screen': stdout and stderr are logged to the screen,
      - 'log': stdout and stderr are logged to launch log file and stderr to
            the screen,
      - 'both': both stdout and stderr are logged to the screen and to launch
            main log file,
      - 'own_log' for stdout, stderr and their combination to be logged to
            their own log files, and
      - 'full' to have stdout and stderr sent to the screen, to the main launch
            log file, and their own separate and combined log files.

    :param process_name: the process-like action whose outputs want to be logged.
    :param output_config: configuration for the output loggers,
        see above for details.
    :returns: a tuple with the stdout and stderr output loggers.
    """
    ...

_Base: Any = ...
class LaunchLogger(_Base):
    all_loggers: List[logging.Logger] = ...
    def __new__(cls, *args, **kwargs):
        ...
    
    def __init__(self, *args, **kwargs) -> None:
        ...
    


def reset() -> None:
    """Reset logging."""
    ...

