"""
This type stub file was generated by pyright.
"""

import types

"""Module with handlers for launch specific logging."""
def with_per_logger_formatting(cls) -> type[_trait]:
    """Add per logger formatting capabilities to the given logging.Handler."""
    class _trait(cls):
        """A logging.Handler subclass to enable per logger formatting."""
        ...
    
    

class _module_wrapper(types.ModuleType):
    """Provide all Python `logging` module handlers with per logger formatting support."""
    def __init__(self, wrapped_module) -> None:
        ...
    
    def __getattr__(self, name) -> Any:
        ...
    


