"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import List, Optional, TYPE_CHECKING, Text, Tuple, Union
from launch import LaunchContext, SomeSubstitutionsType
from launch.substitution import Substitution
from launch.utilities.type_utils import AllowedTypesType, SomeValueType
from launch.utilities.typing_file_path import FilePath
from .parameters_type import EvaluatedParameterValue

"""Module for a description of a Parameter."""
if TYPE_CHECKING:
    ...
class ParameterValue:
    """Describes a ROS parameter value."""
    def __init__(self, value: SomeValueType, *, value_type: Optional[AllowedTypesType] = ...) -> None:
        """
        Construct a parameter value description.

        :param value: Value or substitution that can be resolved to a value.
        :param value_type: Used when `value` is a substitution, to coerce the result.
            Can be one of:
                - Scalar types: int, bool, float, str
                - List types: List[int], List[bool], List[float], List[str]
                - None: will use yaml rules, and check that the result matches one of the above.
        """
        ...
    
    @property
    def value(self) -> SomeValueType:
        """Getter for parameter value."""
        ...
    
    @property
    def value_type(self) -> AllowedTypesType:
        """Getter for parameter value type."""
        ...
    
    def __str__(self) -> Text:
        ...
    
    def evaluate(self, context: LaunchContext) -> EvaluatedParameterValue:
        """Evaluate and return parameter rule."""
        ...
    


class Parameter:
    """Describes a ROS parameter."""
    def __init__(self, name: SomeSubstitutionsType, value: SomeValueType, *, value_type: Optional[AllowedTypesType] = ...) -> None:
        """
        Construct a parameter description.

        :param name: Name of the parameter.
        :param value: Value of the parameter.
        :param value_type: Used when `value` is a substitution, to coerce the result.
            Can be one of:
                - A scalar type: `int`, `str`, `float`, `bool`.
                  `bool` are written like in `yaml`.
                  Both `1` and `1.` are valid floats.
                - An uniform list: `List[int]`, `List[str]`, `List[float]`, `List[bool]`.
                  Lists are written like in `yaml`.
                - `None`, which means that yaml rules will be used.
                  The result of the convertion must be one of the above types,
                  if not `ValueError` is raised.
            If value is not a substitution and this parameter is provided,
            it will be used to check `value` type.
        """
        ...
    
    @property
    def name(self) -> Union[List[Substitution], Text]:
        """Getter for parameter name."""
        ...
    
    @property
    def value(self) -> SomeValueType:
        """Getter for parameter value."""
        ...
    
    @property
    def value_type(self) -> AllowedTypesType:
        """Getter for parameter value type."""
        ...
    
    def __str__(self) -> Text:
        ...
    
    def evaluate(self, context: LaunchContext) -> Tuple[Text, EvaluatedParameterValue]:
        """Evaluate and return parameter rule."""
        ...
    


class ParameterFile:
    """Describes a ROS parameter file."""
    def __init__(self, param_file: Union[FilePath, SomeSubstitutionsType], *, allow_substs: [bool, SomeSubstitutionsType] = ...) -> None:
        """
        Construct a parameter file description.

        :param param_file: Path to a parameter file.
        :param allow_subst: Allow substitutions in the parameter file.
        """
        ...
    
    @property
    def param_file(self) -> Union[FilePath, List[Substitution]]:
        """Getter for parameter file."""
        ...
    
    @property
    def allow_substs(self) -> Union[bool, List[Substitution]]:
        """Getter for allow substitutions argument."""
        ...
    
    def __str__(self) -> Text:
        ...
    
    def evaluate(self, context: LaunchContext) -> Path:
        """Evaluate and return a parameter file path."""
        ...
    
    def cleanup(self) -> None:
        """Delete created temporary files."""
        ...
    
    def __del__(self) -> None:
        ...
    


