"""
This type stub file was generated by pyright.
"""

import pathlib
from typing import Any, Dict, Mapping, Sequence, Union
from launch.some_substitutions_type import SomeSubstitutionsType
from launch.substitution import Substitution
from .parameter_descriptions import Parameter as ParameterDescription, ParameterFile, ParameterValue as ParameterValueDescription

"""Module for ROS parameter types."""
_SingleValueType_types_tuple = ...
_SingleValueType = Union[str, int, float, bool]
_MultiValueType = Union[Sequence[str], Sequence[int], Sequence[float], Sequence[bool], bytes]
SomeParameterFile = Union[SomeSubstitutionsType, pathlib.Path, ParameterFile]
SomeParameterName = Sequence[Union[Substitution, str]]
SomeParameterValue = Union[ParameterValueDescription, SomeSubstitutionsType, Sequence[SomeSubstitutionsType], _SingleValueType, _MultiValueType]
SomeParameterValue_types_tuple = ...
_SomeParametersDict = Mapping[SomeParameterName, Any]
SomeParametersDict = Mapping[SomeParameterName, Union[SomeParameterValue, _SomeParametersDict]]
SomeParameters = Sequence[Union[SomeParameterFile, ParameterDescription, SomeParametersDict]]
ParameterFile = ...
ParameterName = Sequence[Substitution]
ParameterValue = Union[Sequence[Substitution], Sequence[Sequence[Substitution]], _SingleValueType, _MultiValueType, ParameterValueDescription]
ParametersDict = Dict[ParameterName, ParameterValue]
Parameters = Sequence[Union[ParameterFile, ParametersDict, ParameterDescription]]
EvaluatedParameterValue = Union[_SingleValueType, _MultiValueType]
EvaluatedParameters = Sequence[Union[pathlib.Path, ParameterDescription, Dict[str, EvaluatedParameterValue]]]
