"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Tuple
from launch.some_substitutions_type import SomeSubstitutionsType
from launch.substitution import Substitution

"""Module for remap rule types."""
SomeRemapRule = Tuple[SomeSubstitutionsType, SomeSubstitutionsType]
SomeRemapRules = Iterable[SomeRemapRule]
RemapRule = Tuple[Tuple[Substitution, ...], Tuple[Substitution, ...]]
RemapRules = Iterable[RemapRule]
