"""
This type stub file was generated by pyright.
"""

import launch
from typing import List, Optional

"""Module containing ROS specific adapters and their initialization."""
class ROSAdapter:
    """Wraps rclpy API to ease ROS node usage in `launch_ros` actions."""
    def __init__(self, *, argv: Optional[List[str]] = ..., autostart: bool = ...) -> None:
        """
        Construct adapter.

        :param: argv List of global arguments for rclpy context initialization.
        :param: autostart Whether to start adapter on construction or not.
        """
        ...
    
    def start(self) -> None:
        """Start ROS adapter."""
        ...
    
    def shutdown(self) -> None:
        """Shutdown ROS adapter."""
        ...
    
    @property
    def argv(self) -> List[str]:
        ...
    
    @property
    def ros_context(self) -> Context | None:
        ...
    
    @property
    def ros_node(self) -> Node | None:
        ...
    
    @property
    def ros_executor(self) -> SingleThreadedExecutor | None:
        ...
    


def get_ros_adapter(context: launch.LaunchContext) -> Any:
    """
    Get the ROS adapter managed by the given launch context.

    If no adapter is found, one will be created.

    This function is reentrant but concurrent calls on the
    same `context` are not safe.
    """
    ...

def get_ros_node(context: launch.LaunchContext) -> Any:
    """
    Get the ROS node managed by the given launch context.

    If no node is found, one will be created.

    This function is reentrant but concurrent calls on the
    same `context` are not safe.
    """
    ...

