"""
This type stub file was generated by pyright.
"""

from typing import List, Sequence, Text
from ..frontend import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the anonymous name substitution."""
@expose_substitution('anon')
class AnonName(Substitution):
    """
    Generates an anonymous id based on name.

    Name itself is a unique identifier: multiple uses of anon with
    the same parameter name will create the same "anonymized" name
    """
    def __init__(self, name: SomeSubstitutionsType) -> None:
        """Construct an `AnonName` substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `AnonName` substitution."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for name."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by creating/getting the anonymous name."""
        ...
    
    def compute_name(self, id_value: Text) -> Text:
        """Get anonymous name based on id value."""
        ...
    


