"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Optional, Sequence, Text
from ..frontend import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for boolean substitutions."""
@expose_substitution('not')
class NotSubstitution(Substitution):
    """Substitution that returns 'not' of the input boolean value."""
    def __init__(self, value: SomeSubstitutionsType) -> None:
        """Create a NotSubstitution substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `NotSubstitution` substitution."""
        ...
    
    @property
    def value(self) -> List[Substitution]:
        """Getter for value."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution."""
        ...
    


@expose_substitution('and')
class AndSubstitution(Substitution):
    """Substitution that returns 'and' of the input boolean values."""
    def __init__(self, left: SomeSubstitutionsType, right: SomeSubstitutionsType) -> None:
        """Create an AndSubstitution substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `AndSubstitution` substitution."""
        ...
    
    @property
    def left(self) -> List[Substitution]:
        """Getter for left."""
        ...
    
    @property
    def right(self) -> List[Substitution]:
        """Getter for right."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution."""
        ...
    


@expose_substitution('or')
class OrSubstitution(Substitution):
    """Substitution that returns 'or' of the input boolean values."""
    def __init__(self, left: SomeSubstitutionsType, right: SomeSubstitutionsType) -> None:
        """Create an OrSubstitution substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `OrSubstitution` substitution."""
        ...
    
    @property
    def left(self) -> List[Substitution]:
        """Getter for left."""
        ...
    
    @property
    def right(self) -> List[Substitution]:
        """Getter for right."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution."""
        ...
    


@expose_substitution('any')
class AnySubstitution(Substitution):
    """
    Substitutes to the string 'true' if at least one of the input arguments evaluates to true.

    If none of the arguments evaluate to true, then this substitution returns the string 'false'.
    """
    def __init__(self, *args: SomeSubstitutionsType, container: Optional[Iterable[SomeSubstitutionsType]] = ...) -> None:
        """
        Create an AnySubstitution substitution.

        The following string arguments evaluate to true: '1', 'true', 'True', 'on'
        """
        ...
    
    @classmethod
    def parse(cls, data: Iterable[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, Iterable[SomeSubstitutionsType]]]:
        """Parse `AnySubstitution` substitution."""
        ...
    
    @property
    def args(self) -> List[List[Substitution]]:
        """Getter for args."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution."""
        ...
    


@expose_substitution('all')
class AllSubstitution(Substitution):
    """
    Substitutes to the string 'true' if all of the input arguments evaluate to true.

    If any of the arguments evaluates to false, then this substitution returns the string 'false'.
    """
    def __init__(self, *args: SomeSubstitutionsType, container: Optional[Iterable[SomeSubstitutionsType]] = ...) -> None:
        """
        Create an AllSubstitution substitution.

        The following string arguments evaluate to true: '1', 'true', 'True', 'on'
        The following string arguments evaluate to false: '0', 'false', 'False', 'off'
        """
        ...
    
    @classmethod
    def parse(cls, data: Iterable[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, Iterable[SomeSubstitutionsType]]]:
        """Parse `AllSubstitution` substitution."""
        ...
    
    @property
    def args(self) -> List[List[Substitution]]:
        """Getter for args."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution."""
        ...
    


