"""
This type stub file was generated by pyright.
"""

from typing import List, Sequence, Text
from ..frontend.expose import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the Command substitution."""
@expose_substitution('command')
class Command(Substitution):
    """
    Substitution that gets the output of a command as a string.

    If the command is not found or fails a `SubstitutionFailure` error is raised.
    Behavior on stderr output is configurable, see constructor.
    """
    def __init__(self, command: SomeSubstitutionsType, *, on_stderr: SomeSubstitutionsType = ...) -> None:
        """
        Construct a command substitution.

        :param command: command to be executed. The substitutions will be performed, and
            `shlex.split` will be used on the result.
        :param on_stderr: specifies what to do when there is stderr output.
            Can be one of:
            - 'fail': raises `SubstitutionFailere` when stderr output is detected.
            - 'ignore': `stderr` output is ignored.
            - 'warn': The `stderr` output is ignored, but a warning is logged if detected.
            - 'capture': The `stderr` output will be captured, together with stdout.
            It can also be a substitution, that results in one of those four options.
        """
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `Command` substitution."""
        ...
    
    @property
    def command(self) -> List[Substitution]:
        """Getter for command."""
        ...
    
    @property
    def on_stderr(self) -> List[Substitution]:
        """Getter for on_stderr."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by running the command and capturing its output."""
        ...
    


