"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Sequence, Text
from ..frontend.expose import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the EnvironmentVariable substitution."""
@expose_substitution('env')
class EnvironmentVariable(Substitution):
    """
    Substitution that gets an environment variable value as a string.

    If the environment variable is not found, it returns empty string.

    Note that the environment variable is resolved based on the launch context's environment (i.e.,
    ``context.environment``) even though the substitution may be associated with an entity that
    might have a different set of environment variables.
    """
    def __init__(self, name: SomeSubstitutionsType, *, default_value: Optional[SomeSubstitutionsType] = ...) -> None:
        """
        Construct an environment variable substitution.

        :param name: name of the environment variable.
        :param default_value: used when the environment variable doesn't exist.
            If `None`, the substitution is not optional.
        :raises `launch.substitutions.substitution_failure.SubstitutionFailure`:
            If the environment variable doesn't exist and `default_value` is `None`.
        """
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `EnviromentVariable` substitution."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for name."""
        ...
    
    @property
    def default_value(self) -> Optional[List[Substitution]]:
        """Getter for default_value."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by looking up the environment variable."""
        ...
    


