"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, List, Optional, Sequence, Text, Union
from ..frontend import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the EqualsSubstitution substitution."""
@expose_substitution('equals')
class EqualsSubstitution(Substitution):
    """
    Substitution that checks if two inputs are equal.

    Returns 'true' or 'false' strings depending on the result.
    """
    def __init__(self, left: Optional[Union[Any, Iterable[Any]]], right: Optional[Union[Any, Iterable[Any]]]) -> None:
        """Create an EqualsSubstitution substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `EqualsSubstitution` substitution."""
        ...
    
    @property
    def left(self) -> List[Substitution]:
        """Getter for left."""
        ...
    
    @property
    def right(self) -> List[Substitution]:
        """Getter for right."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution."""
        ...
    


