"""
This type stub file was generated by pyright.
"""

from typing import List, Sequence, Text
from ..frontend import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the FileContent substitution."""
@expose_substitution('file-content')
class FileContent(Substitution):
    """
    Substitution that reads the contents of a file.

    If the file is not found a `SubstitutionFailure` error is raised.
    """
    def __init__(self, path: SomeSubstitutionsType) -> None:
        """Create a FileContent substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `FileContent` substitution."""
        ...
    
    @property
    def path(self) -> List[Substitution]:
        """Getter for path."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by evaluating the expression."""
        ...
    


