"""
This type stub file was generated by pyright.
"""

from typing import List, Sequence, Text
from ..frontend import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the FindExecutable substitution."""
@expose_substitution('find-exec')
class FindExecutable(Substitution):
    """
    Substitution that tries to locate an executable on the PATH.

    :raise: SubstitutionFailure when executable not found
    """
    def __init__(self, *, name: SomeSubstitutionsType) -> None:
        """Create a FindExecutable substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `FindExecutable` substitution."""
        ...
    
    @property
    def name(self) -> List[Substitution]:
        """Getter for name."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by locating the executable on the PATH."""
        ...
    


