"""
This type stub file was generated by pyright.
"""

from typing import List, Sequence, Text
from ..frontend import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the IfElseSubstitution substitution."""
@expose_substitution('if')
class IfElseSubstitution(Substitution):
    """
    Substitution that conditionally returns one of two substitutions.

    Depending on whether the condition substitution evaluates to true, either it returns
    the if_value substitution or the else_value substitution.

    Example with a boolean launch configuration:

        .. doctest::

            >>> from launch.substitutions import LaunchConfiguration
            >>> subst = IfElseSubstitution(
            ...     LaunchConfiguration("arg"),
            ...     if_value="arg_evaluated_to_true",
            ...     else_value="arg_evaluated_to_false")

    Combine with boolean substitutions to create more complex conditions.
    Example with multiple boolean launch configurations:

        .. doctest::

            >>> from launch.substitutions import AllSubstitution
            >>> from launch.substitutions import EqualsSubstitution
            >>> from launch.substitutions import LaunchConfiguration
            >>> from launch.substitutions import NotSubstitution
            >>> subst = IfElseSubstitution(
            ...     AllSubstitution(EqualsSubstitution(LaunchConfiguration("arg1"),
            ...                                        LaunchConfiguration("arg2")),
            ...                     NotSubstitution(LaunchConfiguration("arg3"))),
            ...     if_value="all_args_evaluated_to_true",
            ...     else_value="at_least_one_arg_evaluated_to_false")

    """
    def __init__(self, condition: SomeSubstitutionsType, if_value: SomeSubstitutionsType = ..., else_value: SomeSubstitutionsType = ...) -> None:
        """Create a IfElseSubstitution substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[str, SomeSubstitutionsType]]:
        """Parse `IfElseSubstitution` substitution."""
        ...
    
    @property
    def condition(self) -> List[Substitution]:
        """Getter for condition."""
        ...
    
    @property
    def if_value(self) -> List[Substitution]:
        """Getter for if value."""
        ...
    
    @property
    def else_value(self) -> List[Substitution]:
        """Getter for else value."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by evaluating the condition."""
        ...
    


