"""
This type stub file was generated by pyright.
"""

from typing import Sequence, Text
from .path_join_substitution import PathSubstitution
from ..frontend.expose import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType

"""Module for the LaunchLogDir substitution."""
@expose_substitution('launch_log_dir')
@expose_substitution('log_dir')
class LaunchLogDir(PathSubstitution):
    """Substitution that returns the absolute path to the current launch log directory."""
    def __init__(self) -> None:
        """Create a LaunchLogDir substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[Any, Any]]:
        """Parse `LaunchLogDir` substitution."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by returning the path to the current launch log directory."""
        ...
    


