"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, List, Optional, Sequence, Text, Union
from ..frontend import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the LaunchConfiguration substitution."""
@expose_substitution('var')
class LaunchConfiguration(Substitution):
    """Substitution that can access launch configuration variables."""
    def __init__(self, variable_name: SomeSubstitutionsType, *, default: Optional[Union[Any, Iterable[Any]]] = ...) -> None:
        """Create a LaunchConfiguration substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[Any, Any]]:
        """Parse `FindExecutable` substitution."""
        ...
    
    @property
    def variable_name(self) -> List[Substitution]:
        """Getter for variable_name."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """
        Perform the substitution by retrieving the launch configuration, as a string.

        If the launch configuration is not found and a default has been set,
        the default will be returned, as a string.
        """
        ...
    


