"""
This type stub file was generated by pyright.
"""

from typing import Optional, Text
from ..launch_context import LaunchContext
from ..substitution import Substitution

"""Module for the LocalSubstitution substitution."""
class LocalSubstitution(Substitution):
    """Substitution that can access contextual local variables."""
    def __init__(self, expression: Text, description: Optional[Text] = ...) -> None:
        """Create a LocalSubstitution."""
        ...
    
    @property
    def expression(self) -> Text:
        """Getter for expression."""
        ...
    
    @property
    def description(self) -> Optional[Text]:
        """Getter for description."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by retrieving the local variable."""
        ...
    


