"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, Optional, Text, Union
from .equals_substitution import EqualsSubstitution
from ..frontend import expose_substitution
from ..launch_context import LaunchContext

"""Module for the NotEqualsSubstitution substitution."""
@expose_substitution('not-equals')
class NotEqualsSubstitution(EqualsSubstitution):
    """
    Substitution that checks if two inputs are not equal.

    Returns 'true' or 'false' strings depending on the result.
    """
    def __init__(self, left: Optional[Union[Any, Iterable[Any]]], right: Optional[Union[Any, Iterable[Any]]]) -> None:
        """Create a NotEqualsSubstitution substitution."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution."""
        ...
    


