"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Text
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the PathJoinSubstitution substitution."""
class PathJoinSubstitution(Substitution):
    """
    Substitution that join paths, in a platform independent way.

    This takes in a list of path components as substitutions. The substitutions for each path
    component are performed and concatenated, and then all path components are joined.

    For example:

    .. code-block:: python

        PathJoinSubstitution([
            EnvironmentVariable('SOME_DIR'),
            'cfg',
            ['config_', LaunchConfiguration('map'), '.yml']
        ])

    Or:

    .. code-block:: python

        cfg_dir = PathJoinSubstitution([EnvironmentVariable('SOME_DIR'), 'cfg'])
        cfg_file = cfg_dir / ['config_', LaunchConfiguration('map'), '.yml']

    If the ``SOME_DIR`` environment variable was set to ``/home/user/dir`` and the ``map`` launch
    configuration was set to ``my_map``, this would result in a path equal equivalent to (depending
    on the platform):

    .. code-block:: python

        '/home/user/dir/cfg/config_my_map.yml'
    """
    def __init__(self, substitutions: Iterable[SomeSubstitutionsType]) -> None:
        """
        Create a PathJoinSubstitution.

        :param substitutions: the list of path component substitutions to join
        """
        ...
    
    @property
    def substitutions(self) -> List[List[Substitution]]:
        """Getter for variable_name."""
        ...
    
    def __repr__(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitutions and join into a path."""
        ...
    
    def __truediv__(self, additional_path: SomeSubstitutionsType) -> PathJoinSubstitution:
        """Join path substitutions using the / operator, mimicking pathlib.Path operation."""
        ...
    


class PathSubstitution(PathJoinSubstitution):
    """
    Thin wrapper on PathJoinSubstitution for more pathlib.Path-like construction.

    .. code-block:: python

        PathSubstitution(LaunchConfiguration('base_dir')) / 'sub_dir' / 'file_name'

    Which, for ``base_dir:=/my_dir``, results in (depending on the platform):

    .. code-block:: python

        /my_dir/sub_dir/file_name

    """
    def __init__(self, path: SomeSubstitutionsType) -> None:
        """
        Create a PathSubstitution.

        :param path: May be a single text or Substitution element,
        or an Iterable of them which are then joined
        """
        ...
    


