"""
This type stub file was generated by pyright.
"""

from typing import List, Sequence, Text
from ..frontend import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType
from ..substitution import Substitution

"""Module for the PythonExpression substitution."""
@expose_substitution('eval')
class PythonExpression(Substitution):
    """
    Substitution that can access contextual local variables.

    The expression may contain Substitutions, but must return something that can
    be converted to a string with `str()`.
    It also may contain math symbols and functions.
    """
    def __init__(self, expression: SomeSubstitutionsType, python_modules: SomeSubstitutionsType = ...) -> None:
        """Create a PythonExpression substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[Any, Any]]:
        """Parse `PythonExpression` substitution."""
        ...
    
    @property
    def expression(self) -> List[Substitution]:
        """Getter for expression."""
        ...
    
    @property
    def python_modules(self) -> List[Substitution]:
        """Getter for python modules."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by evaluating the expression."""
        ...
    


