"""
This type stub file was generated by pyright.
"""

"""Module for the SubstitutionFailure exception."""
class SubstitutionFailure(RuntimeError):
    """Raised when a Substitution fails."""
    def __init__(self, msg) -> None:
        """Create a SubstitutionFailure error."""
        ...
    


