"""
This type stub file was generated by pyright.
"""

from typing import Text
from ..launch_context import LaunchContext
from ..substitution import Substitution

"""Module for the TextSubstitution substitution."""
class TextSubstitution(Substitution):
    """Substitution that wraps a single string text."""
    def __init__(self, *, text: Text) -> None:
        """Create a TextSubstitution."""
        ...
    
    @property
    def text(self) -> Text:
        """Getter for text."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """Perform the substitution by returning the string itself."""
        ...
    


