"""
This type stub file was generated by pyright.
"""

from typing import Sequence, Text
from .path_join_substitution import PathSubstitution
from ..frontend.expose import expose_substitution
from ..launch_context import LaunchContext
from ..some_substitutions_type import SomeSubstitutionsType

"""Module for the ThisLaunchFileDir substitution."""
@expose_substitution('dirname')
class ThisLaunchFileDir(PathSubstitution):
    """Substitution that returns the absolute path to the current launch file."""
    def __init__(self) -> None:
        """Create a ThisLaunchFileDir substitution."""
        ...
    
    @classmethod
    def parse(cls, data: Sequence[SomeSubstitutionsType]) -> tuple[type[Self], dict[Any, Any]]:
        """Parse `ThisLaunchFileDir` substitution."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this substitution as a string."""
        ...
    
    def perform(self, context: LaunchContext) -> Text:
        """
        Perform the substitution by returning the path to the current launch file.

        If there is no current launch file, i.e. if run from a script, then an
        error is raised.

        :raises `launch.substitutions.substitution_failure.SubstitutionFailure`:
            if not in a launch file
        """
        ...
    


