"""
This type stub file was generated by pyright.
"""

from typing import Callable, TYPE_CHECKING
from ...event import Event
from ...actions import ExecuteLocal

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class ProcessTargetedEvent(Event):
    """Event base class that is targeted at some running process."""
    name = ...
    def __init__(self, *, process_matcher: Callable[[ExecuteLocal], bool]) -> None:
        """
        Create a ProcessTargetedEvent.

        Some standard matchers are also available, like:

        - :func:`launch.events.matches_action()`
        - :func:`launch.events.process.matches_pid()`
        - :func:`launch.events.process.matches_name()`
        - :func:`launch.events.process.matches_executable()`

        :param: process_matcher is a predicate which can determine if an
            ExecuteLocal action matches this event or not
        """
        ...
    
    @property
    def process_matcher(self) -> Callable[[ExecuteLocal], bool]:
        """Getter for process_matcher."""
        ...
    


