"""
This type stub file was generated by pyright.
"""

from .running_process_event import RunningProcessEvent

"""
This type stub file was generated by pyright.
"""
class ProcessIO(RunningProcessEvent):
    """Event emitted when a process generates output on stdout or stderr, or if stdin is used."""
    name = ...
    def __init__(self, *, text: bytes, fd: int, **kwargs) -> None:
        """
        Create a ProcessIO event.

        Unmatched keyword arguments are passed to RunningProcessEvent, see it
        for details on those arguments.

        :param: text is the unicode data associated with the event
        :param: fd is an integer that indicates which file descriptor the text is from
        """
        ...
    
    @property
    def text(self) -> bytes:
        """Getter for text."""
        ...
    
    @property
    def from_stdin(self) -> bool:
        """Getter for from_stdin."""
        ...
    
    @property
    def from_stdout(self) -> bool:
        """Getter for from_stdout."""
        ...
    
    @property
    def from_stderr(self) -> bool:
        """Getter for from_stderr."""
        ...
    


