"""
This type stub file was generated by pyright.
"""

from typing import Callable, TYPE_CHECKING, Text
from ...actions import ExecuteProcess

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
def matches_pid(pid: int) -> Callable[[ExecuteProcess], bool]:
    """Return a matcher which matches based on the pid of the process."""
    ...

def matches_name(name: Text) -> Callable[[ExecuteProcess], bool]:
    """Return a matcher which matches based on the name of the ExecuteProcess action."""
    ...

def matches_executable(executable: Text) -> Callable[[ExecuteProcess], bool]:
    """
    Return a matcher which matches based on the name of the executable for the process.

    The given executable is compared with the first element of the 'cmd' using
    str.endswith().
    So, for example, 'ls' would match either 'ls .' or '/usr/bin/ls .'.
    """
    ...

