"""
This type stub file was generated by pyright.
"""

from .process_io import ProcessIO

"""
This type stub file was generated by pyright.
"""
class ProcessStderr(ProcessIO):
    """Event emitted when a process generates output on stderr."""
    name = ...
    def __init__(self, *, text: bytes, **kwargs) -> None:
        """
        Create a ProcessStderr event.

        Unmatched keyword arguments are passed to ProcessEvent, see it for
        details on those arguments.

        :param: text is the unicode data associated with the event
        """
        ...
    


