"""
This type stub file was generated by pyright.
"""

from .running_process_event import RunningProcessEvent

"""
This type stub file was generated by pyright.
"""
class ProcessExited(RunningProcessEvent):
    """Event emitted when a process exits."""
    name = ...
    def __init__(self, *, returncode: int, **kwargs) -> None:
        """
        Create a ProcessExited event.

        Unmatched keyword arguments are passed to RunningProcessEvent, see it
        for details on those arguments.

        :param: returncode is the returncode of the process
        """
        ...
    
    @property
    def returncode(self) -> int:
        """Getter for returncode."""
        ...
    


