"""
This type stub file was generated by pyright.
"""

from .running_process_event import RunningProcessEvent

"""
This type stub file was generated by pyright.
"""
class ProcessStarted(RunningProcessEvent):
    """Event emitted when a process starts."""
    name = ...
    def __init__(self, **kwargs) -> None:
        """
        Create a ProcessStarted event.

        Unmatched keyword arguments are passed to RunningProcessEvent, see it
        for details on those arguments.
        """
        ...
    


