"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional, TYPE_CHECKING, Text
from ...event import Event
from ...actions import ExecuteProcess

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class RunningProcessEvent(Event):
    """Event base class that is related to some running process."""
    name = ...
    def __init__(self, *, action: ExecuteProcess, name: Text, cmd: List[Text], cwd: Optional[Text], env: Optional[Dict[Text, Text]], pid: int) -> None:
        """
        Create a RunningProcessEvent.

        :param: action is the ExecuteProcess action associated with the event
        :param: name is the final name of the process instance, which is unique
        :param: cmd is the final command after substitution expansion
        :param: cwd is the final working directory after substitution expansion
        :param: env is the final environment variables after substitution expansion
        """
        ...
    
    @property
    def action(self) -> ExecuteProcess:
        """Getter for action."""
        ...
    
    @property
    def execute_process_action(self) -> ExecuteProcess:
        """Getter for execute_process_action."""
        ...
    
    @property
    def process_name(self) -> Text:
        """Getter for process_name."""
        ...
    
    @property
    def cmd(self) -> List[Text]:
        """Getter for cmd."""
        ...
    
    @property
    def cwd(self) -> Optional[Text]:
        """Getter for cwd."""
        ...
    
    @property
    def env(self) -> Optional[Dict[Text, Text]]:
        """Getter for env."""
        ...
    
    @property
    def pid(self) -> int:
        """Getter for pid."""
        ...
    


