"""
This type stub file was generated by pyright.
"""

from typing import Callable, TYPE_CHECKING
from .process_targeted_event import ProcessTargetedEvent
from ...actions import ExecuteLocal

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class ShutdownProcess(ProcessTargetedEvent):
    """
    Event emitted when a process should begin shutting down.

    This event is handled by the launch.actions.ExecuteLocal action, see it
    for details on what happens when this is emitted.

    Also see ProcessTargetedEvent for details on how to target a specific
    process.
    """
    name = ...
    def __init__(self, *, process_matcher: Callable[[ExecuteLocal], bool]) -> None:
        """Create a ShutdownProcess event."""
        ...
    


