"""
This type stub file was generated by pyright.
"""

import signal as signal_module
from typing import Callable, TYPE_CHECKING, Text, Union
from .process_targeted_event import ProcessTargetedEvent
from ...actions import ExecuteLocal

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class SignalProcess(ProcessTargetedEvent):
    """Event emitted when a signal should be sent to a process."""
    name = ...
    def __init__(self, *, signal_number: Union[Text, signal_module.Signals], process_matcher: Callable[[ExecuteLocal], bool]) -> None:
        """
        Create a SignalProcess event.

        Takes an optional process matcher, which can be used to match the
        signal to a process.

        Since Windows does not support SIGKILL, the string 'SIGKILL' can be
        given instead of `signal.SIGKILL`.
        Handlers of this event can then check for the 'SIGKILL' string and do
        the appropriate thing on Windows instead of sending a signal.

        :signal_number: either the string 'SIGKILL' or a signal.Signals
        """
        ...
    
    @property
    def signal(self) -> Union[Text, signal_module.Signals]:
        """Getter for signal, it will be 'SIGKILL' or match something from the signal module."""
        ...
    
    @property
    def signal_name(self) -> Text:
        """
        Getter for signal_name.

        It will be something like (e.g.) 'SIGINT'.
        """
        ...
    


