"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from launch.action import Action
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType
from .node import Node
from ..descriptions import ComposableNode

"""Module for the ComposableNodeContainer action."""
@expose_action('node_container')
class ComposableNodeContainer(Node):
    """Action that executes a container ROS node for composable ROS nodes."""
    def __init__(self, *, name: SomeSubstitutionsType, namespace: SomeSubstitutionsType, composable_node_descriptions: Optional[List[ComposableNode]] = ..., **kwargs) -> None:
        """
        Construct a ComposableNodeContainer action.

        Most arguments are forwarded to :class:`launch_ros.actions.Node`, so see the documentation
        of that class for further details.

        :param: name the name of the node, mandatory for full container node name resolution
        :param: namespace the ROS namespace for this Node, mandatory for full container node
             name resolution
        :param composable_node_descriptions: optional descriptions of composable nodes to be loaded
        """
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Parse node_container."""
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[Action]]:
        """
        Execute the action.

        Most work is delegated to :meth:`launch_ros.actions.Node.execute`, except for the
        composable nodes load action if it applies.
        """
        ...
    


