"""
This type stub file was generated by pyright.
"""

import launch
from typing import List, Optional
from launch import SomeSubstitutionsType
from launch.action import Action
from .node import Node

"""Module for the LifecycleNode action."""
class LifecycleNode(Node):
    """Action that executes a ROS lifecycle node."""
    def __init__(self, *, name: SomeSubstitutionsType, namespace: SomeSubstitutionsType, autostart: bool = ..., **kwargs) -> None:
        """
        Construct a LifecycleNode action.

        Almost all of the arguments are passed to :class:`Node` and eventually
        to :class:`launch.actions.ExecuteProcess`, so see the documentation of
        those classes for additional details.

        This action additionally emits some event(s) in certain circumstances:

        - :class:`launch.events.lifecycle.StateTransition`:

            - this event is emitted when a message is published to the
              "/<name>/transition_event" topic, indicating the lifecycle
              node represented by this action changed state

        This action also handles some events related to lifecycle:

        - :class:`launch.events.lifecycle.ChangeState`

          - this event can be targeted to a single lifecycle node, or more than
            one, or even all lifecycle nodes, and it requests the targeted nodes
            to change state, see its documentation for more details.

        :param name: The name of the lifecycle node.
          Although it defaults to None it is a required parameter and the default will be removed
          in a future release.
        :param namespace: The ROS namespace for this Node
        :param autostart: Whether or not to automatically transition to the 'active' state.
        """
        ...
    
    @property
    def node_autostart(self) -> bool:
        """Getter for autostart."""
        ...
    
    @property
    def is_lifecycle_node(self) -> Literal[True]:
        ...
    
    def get_lifecycle_event_manager(self) -> LifecycleEventManager | None:
        ...
    
    def execute(self, context: launch.LaunchContext) -> Optional[List[Action]]:
        """
        Execute the action.

        Delegated to :meth:`launch.actions.ExecuteProcess.execute`.
        """
        ...
    


