"""
This type stub file was generated by pyright.
"""

import launch
from typing import Iterable, List, Optional, Union
from launch import LaunchContext, SomeSubstitutionsType
from launch.action import Action

class LifecycleTransition(Action):
    """An action that simplifies execution of lifecyle transitions."""
    transition_targets = ...
    def __init__(self, *, lifecycle_node_names: Iterable[SomeSubstitutionsType], transition_ids: Iterable[Union[int, SomeSubstitutionsType]], **kwargs) -> None:
        """
        Construct a LifecycleTransition action.

        The action will execute the passed in lifecycle transition for the
        lifecycle nodes with the indicated node names. The action will emit
        an event that triggers the first lifecycle transition of each node
        wait that the node reaches the transition goal and trigger the next
        transition in the list.
        You need to make sure, that the sequence of lifecyle transition you
        pass in is possible.

        :param lifecycle_node_names: The names of the lifecycle nodes to transition
        :param transitions_ids: The transitions to be executed.
        """
        ...
    
    def execute(self, context: launch.LaunchContext) -> Optional[List[Action]]:
        """
        Execute the LifecycleTransition action.

        :return Returns a list of actions to be executed to achieve specified transitions.
          These are EventHandlers and EventEmitters for ChangeState and
          StateTransition events of the nodes indicated.
        """
        ...
    


def match_node_name_start_goal(node_name: str, start_state: str, goal_state: str) -> Callable[..., Any | bool]:
    ...

def match_node_name_goal(node_name: str, goal_state: str) -> Callable[..., Any | bool]:
    ...

