"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from launch.action import Action
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType
from .composable_node_container import ComposableNodeContainer
from ..descriptions import ComposableNode

"""Module for the LoadComposableNodes action."""
@expose_action('load_composable_node')
class LoadComposableNodes(Action):
    """Action that loads composable ROS nodes into a running container."""
    def __init__(self, *, composable_node_descriptions: List[ComposableNode], target_container: Union[SomeSubstitutionsType, ComposableNodeContainer], **kwargs) -> None:
        """
        Construct a LoadComposableNodes action.

        The container node is expected to provide a `~/_container/load_node` service for
        loading purposes.
        Loading will be performed sequentially.
        When executed, this action will block until the container's load service is available.
        Make sure any LoadComposableNode action is executed only after its container processes
        has started.

        :param composable_node_descriptions: descriptions of composable nodes to be loaded
        :param target_container: the container to load the nodes into
        """
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Parse load_composable_node."""
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[Action]]:
        """Execute the action."""
        ...
    


def get_composable_node_load_request(composable_node_description: ComposableNode, context: LaunchContext) -> LoadNode_Request | None:
    """Get the request that will be sent to the composable node container."""
    ...

