"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Optional
from launch.action import Action
from launch.actions import ExecuteProcess
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType
from launch_ros.parameters_type import SomeParameters
from launch_ros.remap_rule_type import SomeRemapRules

"""Module for the Node action."""
class NodeActionExtension:
    """
    The extension point for launch_ros node action extensions.

    The following properties must be defined:
    * `NAME` (will be set to the entry point name)

    The following methods may be defined:
    * `command_extension`
    * `execute`
    """
    NAME = ...
    EXTENSION_POINT_VERSION = ...
    def __init__(self) -> None:
        ...
    
    def prepare_for_execute(self, context, ros_specific_arguments, node_action) -> tuple[list[Any], Any]:
        """
        Perform any actions prior to the node's process being launched.

        `context` is the context within which the launch is taking place,
        containing amongst other things the command line arguments provided by
        the user.

        `ros_specific_arguments` is a dictionary of command line arguments that
        will be passed to the executable and are specific to ROS.

        `node_action` is the Node action instance that is calling the
        extension.

        This method must return a tuple of command line additions as a list of
        launch.substitutions.TextSubstitution objects, and
        `ros_specific_arguments` with any modifications made to it. If no
        modifications are made, it should return
        `[], ros_specific_arguments`.
        """
        ...
    


@expose_action('node')
class Node(ExecuteProcess):
    """Action that executes a ROS node."""
    UNSPECIFIED_NODE_NAME = ...
    UNSPECIFIED_NODE_NAMESPACE = ...
    def __init__(self, *, executable: SomeSubstitutionsType, package: Optional[SomeSubstitutionsType] = ..., name: Optional[SomeSubstitutionsType] = ..., namespace: Optional[SomeSubstitutionsType] = ..., exec_name: Optional[SomeSubstitutionsType] = ..., parameters: Optional[SomeParameters] = ..., remappings: Optional[SomeRemapRules] = ..., ros_arguments: Optional[Iterable[SomeSubstitutionsType]] = ..., arguments: Optional[Iterable[SomeSubstitutionsType]] = ..., **kwargs) -> None:
        """
        Construct an Node action.

        Many arguments are passed eventually to
        :class:`launch.actions.ExecuteProcess`, so see the documentation of
        that class for additional details.
        However, the `cmd` is not meant to be used, instead use the
        `executable` and `arguments` keyword arguments to this function.

        This action, once executed, delegates most work to the
        :class:`launch.actions.ExecuteProcess`, but it also converts some ROS
        specific arguments into generic command line arguments.

        The launch_ros.substitutions.ExecutableInPackage substitution is used
        to find the executable at runtime, so this Action also raise the
        exceptions that substitution can raise when the package or executable
        are not found.

        If the name is not given (or is None) then no name is passed to
        the node on creation and instead the default name specified within the
        code of the node is used instead.

        The namespace can either be absolute (i.e. starts with /) or
        relative.
        If absolute, then nothing else is considered and this is passed
        directly to the node to set the namespace.
        If relative, the namespace in the 'ros_namespace' LaunchConfiguration
        will be prepended to the given relative node namespace.
        If no namespace is given, then the default namespace `/` is
        assumed.

        The parameters are passed as a list, with each element either a yaml
        file that contains parameter rules (string or pathlib.Path to the full
        path of the file), or a dictionary that specifies parameter rules.
        Keys of the dictionary can be strings or an iterable of Substitutions
        that will be expanded to a string.
        Values in the dictionary can be strings, integers, floats, or tuples
        of Substitutions that will be expanded to a string.
        Additionally, values in the dictionary can be lists of the
        aforementioned types, or another dictionary with the same properties.
        A yaml file with the resulting parameters from the dictionary will be
        written to a temporary file, the path to which will be passed to the
        node.
        Multiple parameter dictionaries/files can be passed: each file path
        will be passed in in order to the node (where the last definition of
        a parameter takes effect).
        However, fully qualified node names override wildcards even when
        specified earlier.
        If `namespace` is not specified, dictionaries are prefixed by a
        wildcard namespace (`/**`) and other specific parameter declarations
        may overwrite it.

        Using `ros_arguments` is equivalent to using `arguments` with a
        prepended '--ros-args' item.

        :param: executable the name of the executable to find if a package
            is provided or otherwise a path to the executable to run.
        :param: package the package in which the node executable can be found
        :param: name the name of the node
        :param: namespace the ROS namespace for this Node
        :param: exec_name the label used to represent the process.
            Defaults to the basename of node executable.
        :param: parameters list of names of yaml files with parameter rules,
            or dictionaries of parameters.
        :param: remappings ordered list of 'to' and 'from' string pairs to be
            passed to the node as ROS remapping rules
        :param: ros_arguments list of ROS arguments for the node
        :param: arguments list of extra arguments for the node
        """
        ...
    
    @staticmethod
    def parse_nested_parameters(params, parser) -> list[Any]:
        """Normalize parameters as expected by Node constructor argument."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Parse node."""
        ...
    
    @property
    def node_package(self) -> SomeSubstitutionsType | None:
        """Getter for node_package."""
        ...
    
    @property
    def node_executable(self) -> SomeSubstitutionsType:
        """Getter for node_executable."""
        ...
    
    @property
    def node_name(self) -> Text:
        """Getter for node_name."""
        ...
    
    def is_node_name_fully_specified(self) -> bool:
        ...
    
    def execute(self, context: LaunchContext) -> Optional[List[Action]]:
        """
        Execute the action.

        Delegated to :meth:`launch.actions.ExecuteProcess.execute`.
        """
        ...
    
    @property
    def expanded_node_namespace(self) -> str:
        """Getter for expanded_node_namespace."""
        ...
    
    @property
    def expanded_remapping_rules(self) -> List[Tuple[Text, Text]] | None:
        """Getter for expanded_remappings."""
        ...
    


def instantiate_extension(group_name, extension_name, extension_class, extensions, logger, *, unique_instance=...) -> None:
    ...

g_entry_points_impl = ...
def get_extensions(logger) -> dict[Any, Any]:
    ...

