"""
This type stub file was generated by pyright.
"""

from typing import List
from launch import Action, Substitution
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType

"""Module for the `PushROSNamespace` action."""
@expose_action('push_ros_namespace')
@expose_action('push-ros-namespace')
class PushROSNamespace(Action):
    """
    Action that pushes the ros namespace.

    It's automatically popped when used inside a scoped `GroupAction`.
    There's no other way of popping it.
    """
    def __init__(self, namespace: SomeSubstitutionsType, **kwargs) -> None:
        """Create a PushROSNamespace action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `PushROSNamespace` action and kwargs for constructing it."""
        ...
    
    @property
    def namespace(self) -> List[Substitution]:
        """Getter for self.__namespace."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


