"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Text, Union
from launch.actions import TimerAction
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.launch_description_entity import LaunchDescriptionEntity
from launch.some_substitutions_type import SomeSubstitutionsType

"""Module for the ROSTimer action."""
@expose_action('ros_timer')
class ROSTimer(TimerAction):
    """
    Action that defers other entities until a period of time has passed, unless canceled.

    This timer uses ROS time instead of wall clock time.
    To enable the use of sim time, you must also use the SetUseSimTime action.
    All timers are "one-shot", in that they only fire one time and never again.
    """
    def __init__(self, *, period: Union[float, SomeSubstitutionsType], actions: Iterable[LaunchDescriptionEntity], **kwargs) -> None:
        """
        Create a ROSTimer.

        :param period: is the time (in seconds) to set the timer for.
        :param actions: is an iterable containing actions to be executed upon on timeout.
        """
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return the `ROSTimer` action and kwargs for constructing it."""
        ...
    
    def describe(self) -> Text:
        """Return a description of this ROSTimer."""
        ...
    
    def execute(self, context: LaunchContext) -> List[LaunchDescriptionEntity] | None:
        ...
    


