"""
This type stub file was generated by pyright.
"""

from typing import List, Union
from launch import Action
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType
from launch.substitution import Substitution

@expose_action('set_use_sim_time')
class SetUseSimTime(Action):
    """Action that sets the 'use_sim_time' parameter in the current context."""
    def __init__(self, value: Union[bool, SomeSubstitutionsType], **kwargs) -> None:
        """Create a SetUseSimTime action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `SetUseSimTime` action and kwargs for constructing it."""
        ...
    
    @property
    def value(self) -> List[Substitution]:
        """Getter for value."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


