"""
This type stub file was generated by pyright.
"""

from typing import List
from launch import Action, Substitution
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType

"""Module for the `SetRemap` action."""
@expose_action('set_remap')
class SetRemap(Action):
    """
    Action that sets a remapping rule in the current context.

    This remapping rule will be passed to all the nodes launched in the same scope, overriding
    the ones specified in the `Node` action constructor.

    For example:

    .. code-block:: python

        LaunchDescription([
            ...,
            GroupAction(
                actions = [
                    ...,
                    SetRemap(src='asd', dst='bsd'),
                    ...,
                    Node(...),  # the remap rule will be passed to this node
                    ...,
                ]
            ),
            Node(...),  # here it won't be passed, as it's not in the same scope
            ...
        ])
    """
    def __init__(self, src: SomeSubstitutionsType, dst: SomeSubstitutionsType, **kwargs) -> None:
        """Create a SetRemap action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `SetRemap` action and kwargs for constructing it."""
        ...
    
    @property
    def src(self) -> List[Substitution]:
        """Getter for src."""
        ...
    
    @property
    def dst(self) -> List[Substitution]:
        """Getter for dst."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


