"""
This type stub file was generated by pyright.
"""

from typing import List
from launch import Action, Substitution
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType

"""Module for the `SetROSLogDir` action."""
@expose_action('set_ros_log_dir')
class SetROSLogDir(Action):
    """
    Action that sets the ros log directory.

    This is done by setting the ROS_LOG_DIR environment variable, which will
    influence all processes started after that time, in which ros was initialized.

    This can be used in combination with launch.actions.GroupAction and its
    ``scoped=true`` option to provide scoped changes to this environment
    variable.

    Note this will not affect nodes loaded into component containers which were
    started before this action is executed.
    """
    def __init__(self, new_log_dir: SomeSubstitutionsType, **kwargs) -> None:
        """
        Create a SetROSLogDir action.

        :param new_log_dir: new log directory, if absolute it sets the ros log dir,
            but if it is a relative path, then it is joined with the current ros log dir.
        """
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `SetROSLogDir` action and kwargs for constructing it."""
        ...
    
    @property
    def log_dir(self) -> List[Substitution]:
        """Getter for self.__log_dir."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


