"""
This type stub file was generated by pyright.
"""

from launch import Action
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType
from launch_ros.parameters_type import ParameterName, ParameterValue, SomeParameterValue

"""Module for the `SetParameter` action."""
@expose_action('set_parameter')
class SetParameter(Action):
    """
    Action that sets a parameter in the current context.

    This parameter will be set in all the nodes launched in the same scope.

    For example:

    .. code-block:: python

        LaunchDescription([
            ...,
            GroupAction(
                actions = [
                    ...,
                    SetParameter(name='my_param', value='2'),
                    ...,
                    Node(...),  # the param will be passed to this node
                    ...,
                ]
            ),
            Node(...),  # here it won't be passed, as it's not in the same scope
            ...
        ])
    """
    def __init__(self, name: SomeSubstitutionsType, value: SomeParameterValue, **kwargs) -> None:
        """Create a SetParameter action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `SetParameter` action and kwargs for constructing it."""
        ...
    
    @property
    def name(self) -> ParameterName:
        """Getter for name."""
        ...
    
    @property
    def value(self) -> ParameterValue:
        """Getter for value."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


