"""
This type stub file was generated by pyright.
"""

from launch import Action
from launch.frontend import Entity, Parser, expose_action
from launch.launch_context import LaunchContext
from launch.some_substitutions_type import SomeSubstitutionsType

"""Module for the `SetParametersFromFile` action."""
@expose_action('set_parameters_from_file')
class SetParametersFromFile(Action):
    """
    Action that sets parameters for all nodes in scope based on a given yaml file.

    For example:

    .. code-block:: python

        LaunchDescription([
            ...,
            GroupAction(
                actions = [
                    ...,
                    SetParametersFromFile('path/to/file.yaml'),
                    ...,
                    Node(...),  # the params will be passed to this node
                    ...,
                ]
            ),
            Node(...),  # here it won't be passed, as it's not in the same scope
            ...
        ])

    .. code-block:: xml

        <launch>
            <group>
                <set_parameters_from_file filename='/path/to/file.yaml'/>
                <node .../>  <!-- Node in scope, params will be passed -->
            </group>
            <node .../>  <!-- Node not in scope, params won't be passed -->
        </launch>
    """
    def __init__(self, filename: SomeSubstitutionsType, **kwargs) -> None:
        """Create a SetParameterFromFile action."""
        ...
    
    @classmethod
    def parse(cls, entity: Entity, parser: Parser) -> tuple[type[Self], Dict[str, Condition]]:
        """Return `SetParameterFromFile` action and kwargs for constructing it."""
        ...
    
    def execute(self, context: LaunchContext) -> None:
        """Execute the action."""
        ...
    


