"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, Text
from launch.event import Event
from launch.event_handler import EventHandler
from launch.some_entities_type import SomeEntitiesType
from launch.some_substitutions_type import SomeSubstitutionsType

"""Module for OnStateTransition class."""
class OnStateTransition(EventHandler):
    """Convenience class for handling a state transition of a lifecycle node."""
    def __init__(self, *, entities: SomeEntitiesType, target_lifecycle_node: Optional[LifecycleNode] = ..., transition: Optional[SomeSubstitutionsType] = ..., start_state: Optional[SomeSubstitutionsType] = ..., goal_state: Optional[SomeSubstitutionsType] = ..., matcher: Optional[Callable[[Event], bool]] = ..., **kwargs) -> None:
        """
        Create an OnStateTransition event handler.

        There are several matching options, each of which is compared with the
        event and must match it to have the handler handle the event.
        Passing None for any of them will prevent that matching option from
        being considered (and therefore not required) when matching the event.

        If matcher is given, the other conditions are not considered.
        """
        ...
    
    @property
    def handler_description(self) -> Text:
        """Return the string description of the handler."""
        ...
    
    @property
    def matcher_description(self) -> str:
        """Return the string description of the matcher."""
        ...
    


