"""
This type stub file was generated by pyright.
"""

from typing import Callable
from launch.event import Event

"""Module for ChangeState event."""
if False:
    ...
class ChangeState(Event):
    """Event emitted when a state transition is requested for a lifecycle node."""
    name = ...
    valid_transitions = ...
    valid_states = ...
    def __init__(self, *, lifecycle_node_matcher: Callable[[LifecycleNode], bool], transition_id: int) -> None:
        """
        Create a ChangeState event.

        :param: lifecycle_node_matcher is a callable which returns True if the
            given lifecycle node should be affected by this event.
        :param: transition_id is the id of the requested transition which are
            defined in the :class:`lifecycle_msgs.msg.Transition` message class,
            e.g. `lifecycle_msgs.msg.Transition.TRANSITION_CONFIGURE`.
        """
        ...
    
    @property
    def lifecycle_node_matcher(self) -> Callable[[LifecycleNode], bool]:
        """Getter for lifecycle_node_matcher."""
        ...
    
    @property
    def transition_id(self) -> int:
        """Getter for transition_id."""
        ...
    


