"""
This type stub file was generated by pyright.
"""

from typing import Callable, Text

"""Module for standard "lifecycle_node_matchers", which are used with targeted lifecycle events."""
if False:
    ...
def matches_node_name(node_name: Text) -> Callable[[LifecycleNode], bool]:
    """Return a matcher which matches based on the name of the node itself."""
    ...

