"""
This type stub file was generated by pyright.
"""

import lifecycle_msgs.msg
from typing import Text
from launch.event import Event

"""Module for StateTransition event."""
if False:
    ...
class StateTransition(Event):
    """Event emitted when a lifecycle node makes a state transition."""
    name = ...
    def __init__(self, *, action: LifecycleNode, msg: lifecycle_msgs.msg.TransitionEvent) -> None:
        """
        Create a StateTransition event.

        :param: action the instance of class::`LifecycleNode` that generated this event
        :param: msg the instance of the ROS message TransitionEvent that generated this event
        """
        ...
    
    @property
    def action(self) -> LifecycleNode:
        """Getter for action."""
        ...
    
    @property
    def msg(self) -> lifecycle_msgs.msg.TransitionEvent:
        """Getter for msg."""
        ...
    
    @property
    def timestamp(self) -> int:
        """Getter for timestamp."""
        ...
    
    @property
    def transition(self) -> Text:
        """Getter for transition."""
        ...
    
    @property
    def start_state(self) -> Text:
        """Getter for start_state."""
        ...
    
    @property
    def goal_state(self) -> Text:
        """Getter for goal_state."""
        ...
    


