"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from launch.condition import Condition
from launch.frontend import Entity, Parser
from launch.some_substitutions_type import SomeSubstitutionsType
from launch.substitution import Substitution
from launch_ros.parameters_type import Parameters, SomeParameters
from launch_ros.remap_rule_type import RemapRules, SomeRemapRules

"""Module for a description of a ComposableNode."""
class ComposableNode:
    """Describes a ROS node that can be loaded into a container with other nodes."""
    def __init__(self, *, package: SomeSubstitutionsType, plugin: SomeSubstitutionsType, name: Optional[SomeSubstitutionsType] = ..., namespace: Optional[SomeSubstitutionsType] = ..., parameters: Optional[SomeParameters] = ..., remappings: Optional[SomeRemapRules] = ..., extra_arguments: Optional[SomeParameters] = ..., condition: Optional[Condition] = ...) -> None:
        """
        Initialize a ComposableNode description.

        :param package: name of the ROS package the node plugin lives in
        :param plugin: name of the plugin to be loaded
        :param name: name to give to the ROS node
        :param namespace: namespace to give to the ROS node
        :param parameters: list of either paths to yaml files or dictionaries of parameters
        :param remappings: list of from/to pairs for remapping names
        :param extra_arguments: container specific arguments to be passed to the loaded node
        :param condition: action will be executed if the condition evaluates to true
        """
        ...
    
    @classmethod
    def parse(cls, parser: Parser, entity: Entity) -> tuple[type[Self], dict[Any, Any]]:
        """Parse composable_node."""
        ...
    
    @property
    def package(self) -> List[Substitution]:
        """Get node package name as a sequence of substitutions to be performed."""
        ...
    
    @property
    def node_plugin(self) -> List[Substitution]:
        """Get node plugin name as a sequence of substitutions to be performed."""
        ...
    
    @property
    def node_name(self) -> Optional[List[Substitution]]:
        """Get node name as a sequence of substitutions to be performed."""
        ...
    
    @property
    def node_namespace(self) -> Optional[List[Substitution]]:
        """Get node namespace as a sequence of substitutions to be performed."""
        ...
    
    @property
    def parameters(self) -> Optional[Parameters]:
        """Get node parameter YAML files or dicts with substitutions to be performed."""
        ...
    
    @property
    def remappings(self) -> Optional[RemapRules]:
        """Get node remapping rules as (from, to) tuples with substitutions to be performed."""
        ...
    
    @property
    def extra_arguments(self) -> Optional[Parameters]:
        """Get container extra arguments YAML files or dicts with substitutions to be performed."""
        ...
    
    def condition(self) -> Optional[Condition]:
        """Getter for condition."""
        ...
    


