"""
This type stub file was generated by pyright.
"""

import launch
from typing import List, Optional
from launch.substitution import Substitution
from launch_ros.parameters_type import Parameters
from launch_ros.remap_rule_type import RemapRules
from .composable_node import ComposableNode

"""Module for a description of a ComposableLifecycleNode."""
class ComposableLifecycleNode(ComposableNode):
    """Describes a lifecycle node that can be loaded into a container with other nodes."""
    def __init__(self, *, autostart: bool = ..., **kwargs) -> None:
        """
        Initialize a ComposableLifecycleNode description.

        :param autostart: Whether to autostart lifecycle node in the activated state
        """
        ...
    
    def init_lifecycle_event_manager(self, context: launch.LaunchContext) -> None:
        ...
    
    @property
    def package(self) -> List[Substitution]:
        """Get node package name as a sequence of substitutions to be performed."""
        ...
    
    @property
    def node_plugin(self) -> List[Substitution]:
        """Get node plugin name as a sequence of substitutions to be performed."""
        ...
    
    @property
    def node_name(self) -> Optional[List[Substitution]]:
        """Get node name as a sequence of substitutions to be performed."""
        ...
    
    @property
    def node_namespace(self) -> Optional[List[Substitution]]:
        """Get node namespace as a sequence of substitutions to be performed."""
        ...
    
    @property
    def node_autostart(self) -> bool:
        """Getter for autostart."""
        ...
    
    @property
    def parameters(self) -> Optional[Parameters]:
        """Get node parameter YAML files or dicts with substitutions to be performed."""
        ...
    
    @property
    def remappings(self) -> Optional[RemapRules]:
        """Get node remapping rules as (from, to) tuples with substitutions to be performed."""
        ...
    
    @property
    def extra_arguments(self) -> Optional[Parameters]:
        """Get container extra arguments YAML files or dicts with substitutions to be performed."""
        ...
    


